/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptDealRequest,
  CloseDealRequest,
  DealDetailsResponse,
  ErrorResponse,
  LostDealRequest,
  OfferMadeRequest,
  ReasonResponse,
  RejectDealRequest,
  ValidateDealDataRequest,
} from '../models/index';
import {
    AcceptDealRequestFromJSON,
    AcceptDealRequestToJSON,
    CloseDealRequestFromJSON,
    CloseDealRequestToJSON,
    DealDetailsResponseFromJSON,
    DealDetailsResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LostDealRequestFromJSON,
    LostDealRequestToJSON,
    OfferMadeRequestFromJSON,
    OfferMadeRequestToJSON,
    ReasonResponseFromJSON,
    ReasonResponseToJSON,
    RejectDealRequestFromJSON,
    RejectDealRequestToJSON,
    ValidateDealDataRequestFromJSON,
    ValidateDealDataRequestToJSON,
} from '../models/index';

export interface AcceptDealOperationRequest {
    id: string;
    xXORGID: string;
    acceptDealRequest: AcceptDealRequest;
}

export interface AgreementActivatedRequest {
    id: string;
    xXORGID: string;
}

export interface CloseDeal1Request {
    id: string;
    xXORGID: string;
    closeDealRequest: CloseDealRequest;
}

export interface FindDealsRequest {
    xXORGID: string;
    organisationId?: string;
    hubspotDealId?: string;
}

export interface GetDeal1Request {
    id: string;
    xXORGID: string;
}

export interface GetLatestChangesRequest {
    type: GetLatestChangesTypeEnum;
    xXORGID: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetLostReasonsRequest {
    xXORGID: string;
}

export interface GetRejectionReasonsRequest {
    xXORGID: string;
}

export interface LostDeal1Request {
    id: string;
    xXORGID: string;
    lostDealRequest: LostDealRequest;
}

export interface OfferMadeForDealRequest {
    id: string;
    xXORGID: string;
    offerMadeRequest: OfferMadeRequest;
}

export interface RejectDeal1Request {
    id: string;
    xXORGID: string;
    rejectDealRequest: RejectDealRequest;
}

export interface StartDueDiligenceRequest {
    id: string;
    xXORGID: string;
}

export interface ValidateDealDataOperationRequest {
    id: string;
    xXORGID: string;
    validateDealDataRequest: ValidateDealDataRequest;
}

/**
 * 
 */
export class AdminDealControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     */
    async acceptDealRaw(requestParameters: AcceptDealOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling acceptDeal().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling acceptDeal().'
            );
        }

        if (requestParameters['acceptDealRequest'] == null) {
            throw new runtime.RequiredError(
                'acceptDealRequest',
                'Required parameter "acceptDealRequest" was null or undefined when calling acceptDeal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/accept`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptDealRequestToJSON(requestParameters['acceptDealRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async acceptDeal(requestParameters: AcceptDealOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.acceptDealRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async agreementActivatedRaw(requestParameters: AgreementActivatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agreementActivated().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling agreementActivated().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/start-loan-repayment`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async agreementActivated(requestParameters: AgreementActivatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agreementActivatedRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async closeDeal1Raw(requestParameters: CloseDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling closeDeal1().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling closeDeal1().'
            );
        }

        if (requestParameters['closeDealRequest'] == null) {
            throw new runtime.RequiredError(
                'closeDealRequest',
                'Required parameter "closeDealRequest" was null or undefined when calling closeDeal1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/close`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CloseDealRequestToJSON(requestParameters['closeDealRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async closeDeal1(requestParameters: CloseDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.closeDeal1Raw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async findDealsRaw(requestParameters: FindDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling findDeals().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['organisationId'] != null) {
            queryParameters['organisationId'] = requestParameters['organisationId'];
        }

        if (requestParameters['hubspotDealId'] != null) {
            queryParameters['hubspotDealId'] = requestParameters['hubspotDealId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/find`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async findDeals(requestParameters: FindDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.findDealsRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async getDeal1Raw(requestParameters: GetDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DealDetailsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeal1().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getDeal1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DealDetailsResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getDeal1(requestParameters: GetDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DealDetailsResponse> {
        const response = await this.getDeal1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getLatestChangesRaw(requestParameters: GetLatestChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getLatestChanges().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getLatestChanges().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/latest-changes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async getLatestChanges(requestParameters: GetLatestChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getLatestChangesRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async getLostReasonsRaw(requestParameters: GetLostReasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReasonResponse>>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getLostReasons().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/lost-reasons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReasonResponseFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getLostReasons(requestParameters: GetLostReasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReasonResponse>> {
        const response = await this.getLostReasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getRejectionReasonsRaw(requestParameters: GetRejectionReasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReasonResponse>>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getRejectionReasons().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/rejection-reasons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReasonResponseFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getRejectionReasons(requestParameters: GetRejectionReasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReasonResponse>> {
        const response = await this.getRejectionReasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async lostDeal1Raw(requestParameters: LostDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lostDeal1().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling lostDeal1().'
            );
        }

        if (requestParameters['lostDealRequest'] == null) {
            throw new runtime.RequiredError(
                'lostDealRequest',
                'Required parameter "lostDealRequest" was null or undefined when calling lostDeal1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/lost`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LostDealRequestToJSON(requestParameters['lostDealRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async lostDeal1(requestParameters: LostDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lostDeal1Raw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async offerMadeForDealRaw(requestParameters: OfferMadeForDealRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling offerMadeForDeal().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling offerMadeForDeal().'
            );
        }

        if (requestParameters['offerMadeRequest'] == null) {
            throw new runtime.RequiredError(
                'offerMadeRequest',
                'Required parameter "offerMadeRequest" was null or undefined when calling offerMadeForDeal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/offer-made`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OfferMadeRequestToJSON(requestParameters['offerMadeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async offerMadeForDeal(requestParameters: OfferMadeForDealRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.offerMadeForDealRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async rejectDeal1Raw(requestParameters: RejectDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rejectDeal1().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling rejectDeal1().'
            );
        }

        if (requestParameters['rejectDealRequest'] == null) {
            throw new runtime.RequiredError(
                'rejectDealRequest',
                'Required parameter "rejectDealRequest" was null or undefined when calling rejectDeal1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/reject`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RejectDealRequestToJSON(requestParameters['rejectDealRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async rejectDeal1(requestParameters: RejectDeal1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rejectDeal1Raw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async startDueDiligenceRaw(requestParameters: StartDueDiligenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startDueDiligence().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling startDueDiligence().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/start-due-diligence`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async startDueDiligence(requestParameters: StartDueDiligenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startDueDiligenceRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async validateDealDataRaw(requestParameters: ValidateDealDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling validateDealData().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling validateDealData().'
            );
        }

        if (requestParameters['validateDealDataRequest'] == null) {
            throw new runtime.RequiredError(
                'validateDealDataRequest',
                'Required parameter "validateDealDataRequest" was null or undefined when calling validateDealData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/deals/{id}/validate`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateDealDataRequestToJSON(requestParameters['validateDealDataRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async validateDealData(requestParameters: ValidateDealDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validateDealDataRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetLatestChangesTypeEnum = {
    AmountUpdated: 'AMOUNT_UPDATED',
    AttributeUpdated: 'ATTRIBUTE_UPDATED',
    DealClosed: 'DEAL_CLOSED',
    DealCreated: 'DEAL_CREATED',
    DealEnteredDataValidation: 'DEAL_ENTERED_DATA_VALIDATION',
    DealEnteredDueDiligence: 'DEAL_ENTERED_DUE_DILIGENCE',
    DealEnteredLoanRepayment: 'DEAL_ENTERED_LOAN_REPAYMENT',
    DealEnteredOffering: 'DEAL_ENTERED_OFFERING',
    DealEnteredUnderwriting: 'DEAL_ENTERED_UNDERWRITING',
    DealLost: 'DEAL_LOST',
    DealReenteredDataCompleteness: 'DEAL_REENTERED_DATA_COMPLETENESS',
    DealRejected: 'DEAL_REJECTED',
    HubspotDealIdAssigned: 'HUBSPOT_DEAL_ID_ASSIGNED',
    TierUpdated: 'TIER_UPDATED',
    NameUpdated: 'NAME_UPDATED',
    SellersFiDealImported: 'SELLERS_FI_DEAL_IMPORTED'
} as const;
export type GetLatestChangesTypeEnum = typeof GetLatestChangesTypeEnum[keyof typeof GetLatestChangesTypeEnum];
