/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DealWithOwner,
} from '../models/index';
import {
    DealWithOwnerFromJSON,
    DealWithOwnerToJSON,
} from '../models/index';

export interface GetCompanyDealsWithOwnerRequest {
    companyId: string;
    xXORGID: string;
}

/**
 * 
 */
export class CrmDealWithAssociationsControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     */
    async getCompanyDealsWithOwnerRaw(requestParameters: GetCompanyDealsWithOwnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DealWithOwner>>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getCompanyDealsWithOwner().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCompanyDealsWithOwner().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crm/deals-with-associations/company/{companyId}/with-owner`;
        urlPath = urlPath.replace(`{${"companyId"}}`, encodeURIComponent(String(requestParameters['companyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DealWithOwnerFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getCompanyDealsWithOwner(requestParameters: GetCompanyDealsWithOwnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DealWithOwner>> {
        const response = await this.getCompanyDealsWithOwnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
