/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DealDto,
} from '../models/index';
import {
    DealDtoFromJSON,
    DealDtoToJSON,
} from '../models/index';

export interface GetCompanyDealsRequest {
    companyId: string;
    xXORGID: string;
}

export interface GetDealRequest {
    dealId: string;
    xXORGID: string;
}

/**
 * 
 */
export class CrmDealControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     */
    async getCompanyDealsRaw(requestParameters: GetCompanyDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DealDto>>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getCompanyDeals().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCompanyDeals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crm/deals/company/{companyId}`;
        urlPath = urlPath.replace(`{${"companyId"}}`, encodeURIComponent(String(requestParameters['companyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DealDtoFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getCompanyDeals(requestParameters: GetCompanyDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DealDto>> {
        const response = await this.getCompanyDealsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getDealRaw(requestParameters: GetDealRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DealDto>> {
        if (requestParameters['dealId'] == null) {
            throw new runtime.RequiredError(
                'dealId',
                'Required parameter "dealId" was null or undefined when calling getDeal().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getDeal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crm/deals/{dealId}`;
        urlPath = urlPath.replace(`{${"dealId"}}`, encodeURIComponent(String(requestParameters['dealId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DealDtoFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getDeal(requestParameters: GetDealRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DealDto> {
        const response = await this.getDealRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
