/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebhookEvent,
} from '../models/index';
import {
    WebhookEventFromJSON,
    WebhookEventToJSON,
} from '../models/index';

export interface WebhookRequest {
    xXORGID: string;
    webhookEvent: Array<WebhookEvent>;
    token?: string;
}

/**
 * 
 */
export class WebhookControllerApi extends runtime.BaseAPI {

    /**
     * This API is **public**.
     */
    async webhookRaw(requestParameters: WebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling webhook().'
            );
        }

        if (requestParameters['webhookEvent'] == null) {
            throw new runtime.RequiredError(
                'webhookEvent',
                'Required parameter "webhookEvent" was null or undefined when calling webhook().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/webhook`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['webhookEvent']!.map(WebhookEventToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API is **public**.
     */
    async webhook(requestParameters: WebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhookRaw(requestParameters, initOverrides);
    }

}
