/* tslint:disable */
/* eslint-disable */
/**
 * api-kyc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorMessageDTO,
  PhotoMetadataNewDTO,
} from '../models/index';
import {
    ErrorMessageDTOFromJSON,
    ErrorMessageDTOToJSON,
    PhotoMetadataNewDTOFromJSON,
    PhotoMetadataNewDTOToJSON,
} from '../models/index';

export interface GetApplicantPhotoRequest {
    uuid: string;
    photoId: string;
    xXORGID: string;
}

export interface UploadApplicantPhotoRequest {
    uuid: string;
    xXORGID: string;
    metadata: PhotoMetadataNewDTO;
    file: Blob;
}

/**
 * 
 */
export class ApplicantPhotoControllerApi extends runtime.BaseAPI {

    /**
     * This API is **public**.
     * Get photo document
     */
    async getApplicantPhotoRaw(requestParameters: GetApplicantPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getApplicantPhoto().'
            );
        }

        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling getApplicantPhoto().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getApplicantPhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/applicantData/{uuid}/document/{photoId}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))).replace(`{${"photoId"}}`, encodeURIComponent(String(requestParameters['photoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API is **public**.
     * Get photo document
     */
    async getApplicantPhoto(requestParameters: GetApplicantPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getApplicantPhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API is **public**.
     */
    async uploadApplicantPhotoRaw(requestParameters: UploadApplicantPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling uploadApplicantPhoto().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling uploadApplicantPhoto().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling uploadApplicantPhoto().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadApplicantPhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['metadata'] != null) {
            formParams.append('metadata', new Blob([JSON.stringify(PhotoMetadataNewDTOToJSON(requestParameters['metadata']))], { type: "application/json", }));
                    }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/applicantData/{uuid}/document`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API is **public**.
     */
    async uploadApplicantPhoto(requestParameters: UploadApplicantPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.uploadApplicantPhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
