/* tslint:disable */
/* eslint-disable */
/**
 * api-partners
 * Change log: <br>1.0.0 initial release
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationCreationRequest
 */
export interface OrganisationCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     */
    businessName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     */
    businessWebsite?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     * @deprecated
     */
    businessType?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof OrganisationCreationRequest
     */
    businessTypes?: Set<OrganisationCreationRequestBusinessTypesEnum>;
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     */
    businessEntity?: OrganisationCreationRequestBusinessEntityEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     */
    country: string;
    /**
     * 
     * @type {number}
     * @memberof OrganisationCreationRequest
     */
    revenue: number;
    /**
     * 
     * @type {string}
     * @memberof OrganisationCreationRequest
     */
    mainEcommercePlatform?: OrganisationCreationRequestMainEcommercePlatformEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganisationCreationRequest
     */
    regions?: Array<string>;
}


/**
 * @export
 */
export const OrganisationCreationRequestBusinessTypesEnum = {
    EcommerceAmazonMarketplace: 'ECOMMERCE_AMAZON_MARKETPLACE',
    RetailWholesale: 'RETAIL_WHOLESALE',
    SubscriptionSaas: 'SUBSCRIPTION_SAAS',
    Other: 'OTHER'
} as const;
export type OrganisationCreationRequestBusinessTypesEnum = typeof OrganisationCreationRequestBusinessTypesEnum[keyof typeof OrganisationCreationRequestBusinessTypesEnum];

/**
 * @export
 */
export const OrganisationCreationRequestBusinessEntityEnum = {
    GbrPrivateLimitedCompany: 'GBR_PRIVATE_LIMITED_COMPANY',
    GbrPublicLimitedCompany: 'GBR_PUBLIC_LIMITED_COMPANY',
    GbrCompanyLimitedByGuarantee: 'GBR_COMPANY_LIMITED_BY_GUARANTEE',
    GbrUnlimitedCompany: 'GBR_UNLIMITED_COMPANY',
    GbrLimitedLiabilityPartnership: 'GBR_LIMITED_LIABILITY_PARTNERSHIP',
    GbrCommunityInterestCompany: 'GBR_COMMUNITY_INTEREST_COMPANY',
    GbrIndustrialAndProvidentSociety: 'GBR_INDUSTRIAL_AND_PROVIDENT_SOCIETY',
    GbrSoleTrader: 'GBR_SOLE_TRADER',
    GbrOther: 'GBR_OTHER',
    UsaSoleProprietorship: 'USA_SOLE_PROPRIETORSHIP',
    UsaPartnership: 'USA_PARTNERSHIP',
    UsaCCorporation: 'USA_C_CORPORATION',
    UsaSCorporation: 'USA_S_CORPORATION',
    UsaLimitedLiabilityCompany: 'USA_LIMITED_LIABILITY_COMPANY',
    UsaLimitedLiabilityPartership: 'USA_LIMITED_LIABILITY_PARTERSHIP',
    UsaOther: 'USA_OTHER',
    PolandRegisteredPartnership: 'POLAND_REGISTERED_PARTNERSHIP',
    PolandProfessionalPartnership: 'POLAND_PROFESSIONAL_PARTNERSHIP',
    PolandLimitedPartnership: 'POLAND_LIMITED_PARTNERSHIP',
    PolandLimitedJointStockPartnership: 'POLAND_LIMITED_JOINT_STOCK_PARTNERSHIP',
    PolandLimitedLiabilityCompany: 'POLAND_LIMITED_LIABILITY_COMPANY',
    PolandJointStockCompany: 'POLAND_JOINT_STOCK_COMPANY',
    PolandSoleProprietorship: 'POLAND_SOLE_PROPRIETORSHIP',
    PolandOther: 'POLAND_OTHER',
    GermanyLimitedLiabilityCompany: 'GERMANY_LIMITED_LIABILITY_COMPANY',
    GermanyLimitedLiabilityEntrepreneurialCompany: 'GERMANY_LIMITED_LIABILITY_ENTREPRENEURIAL_COMPANY',
    GermanyStockCorporation: 'GERMANY_STOCK_CORPORATION',
    GermanyGeneralPartnership: 'GERMANY_GENERAL_PARTNERSHIP',
    GermanyLimitedPartnership: 'GERMANY_LIMITED_PARTNERSHIP',
    GermanySoleProprietorship: 'GERMANY_SOLE_PROPRIETORSHIP',
    GermanyOther: 'GERMANY_OTHER',
    SoleTrader: 'SOLE_TRADER',
    NotSoleTrader: 'NOT_SOLE_TRADER'
} as const;
export type OrganisationCreationRequestBusinessEntityEnum = typeof OrganisationCreationRequestBusinessEntityEnum[keyof typeof OrganisationCreationRequestBusinessEntityEnum];

/**
 * @export
 */
export const OrganisationCreationRequestMainEcommercePlatformEnum = {
    Amazon: 'Amazon',
    Shopify: 'Shopify',
    WooCommerce: 'WooCommerce',
    Other: 'Other'
} as const;
export type OrganisationCreationRequestMainEcommercePlatformEnum = typeof OrganisationCreationRequestMainEcommercePlatformEnum[keyof typeof OrganisationCreationRequestMainEcommercePlatformEnum];


/**
 * Check if a given object implements the OrganisationCreationRequest interface.
 */
export function instanceOfOrganisationCreationRequest(value: object): value is OrganisationCreationRequest {
    if (!('businessName' in value) || value['businessName'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    return true;
}

export function OrganisationCreationRequestFromJSON(json: any): OrganisationCreationRequest {
    return OrganisationCreationRequestFromJSONTyped(json, false);
}

export function OrganisationCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'businessName': json['businessName'],
        'businessWebsite': json['businessWebsite'] == null ? undefined : json['businessWebsite'],
        'businessType': json['businessType'] == null ? undefined : json['businessType'],
        'businessTypes': json['businessTypes'] == null ? undefined : new Set(json['businessTypes']),
        'businessEntity': json['businessEntity'] == null ? undefined : json['businessEntity'],
        'country': json['country'],
        'revenue': json['revenue'],
        'mainEcommercePlatform': json['mainEcommercePlatform'] == null ? undefined : json['mainEcommercePlatform'],
        'regions': json['regions'] == null ? undefined : json['regions'],
    };
}

export function OrganisationCreationRequestToJSON(json: any): OrganisationCreationRequest {
    return OrganisationCreationRequestToJSONTyped(json, false);
}

export function OrganisationCreationRequestToJSONTyped(value?: OrganisationCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'businessName': value['businessName'],
        'businessWebsite': value['businessWebsite'],
        'businessType': value['businessType'],
        'businessTypes': value['businessTypes'] == null ? undefined : Array.from(value['businessTypes'] as Set<any>),
        'businessEntity': value['businessEntity'],
        'country': value['country'],
        'revenue': value['revenue'],
        'mainEcommercePlatform': value['mainEcommercePlatform'],
        'regions': value['regions'],
    };
}

