/* tslint:disable */
/* eslint-disable */
/**
 * api-partners
 * Change log: <br>1.0.0 initial release
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCompanyUpdateFromRegistryRequest
 */
export interface PartnerCompanyUpdateFromRegistryRequest {
    /**
     * 
     * @type {string}
     * @memberof PartnerCompanyUpdateFromRegistryRequest
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCompanyUpdateFromRegistryRequest
     */
    country: string;
}

/**
 * Check if a given object implements the PartnerCompanyUpdateFromRegistryRequest interface.
 */
export function instanceOfPartnerCompanyUpdateFromRegistryRequest(value: object): value is PartnerCompanyUpdateFromRegistryRequest {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function PartnerCompanyUpdateFromRegistryRequestFromJSON(json: any): PartnerCompanyUpdateFromRegistryRequest {
    return PartnerCompanyUpdateFromRegistryRequestFromJSONTyped(json, false);
}

export function PartnerCompanyUpdateFromRegistryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCompanyUpdateFromRegistryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'country': json['country'],
    };
}

export function PartnerCompanyUpdateFromRegistryRequestToJSON(json: any): PartnerCompanyUpdateFromRegistryRequest {
    return PartnerCompanyUpdateFromRegistryRequestToJSONTyped(json, false);
}

export function PartnerCompanyUpdateFromRegistryRequestToJSONTyped(value?: PartnerCompanyUpdateFromRegistryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'country': value['country'],
    };
}

