/* tslint:disable */
/* eslint-disable */
/**
 * api-partners
 * Change log: <br>1.0.0 initial release
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerDetailsResponse } from './PartnerDetailsResponse';
import {
    PartnerDetailsResponseFromJSON,
    PartnerDetailsResponseFromJSONTyped,
    PartnerDetailsResponseToJSON,
    PartnerDetailsResponseToJSONTyped,
} from './PartnerDetailsResponse';
import type { PartnerUserDetailsResponse } from './PartnerUserDetailsResponse';
import {
    PartnerUserDetailsResponseFromJSON,
    PartnerUserDetailsResponseFromJSONTyped,
    PartnerUserDetailsResponseToJSON,
    PartnerUserDetailsResponseToJSONTyped,
} from './PartnerUserDetailsResponse';

/**
 * 
 * @export
 * @interface PartnerCreationResponse
 */
export interface PartnerCreationResponse {
    /**
     * 
     * @type {PartnerDetailsResponse}
     * @memberof PartnerCreationResponse
     */
    partner?: PartnerDetailsResponse;
    /**
     * 
     * @type {Array<PartnerUserDetailsResponse>}
     * @memberof PartnerCreationResponse
     */
    users?: Array<PartnerUserDetailsResponse>;
}

/**
 * Check if a given object implements the PartnerCreationResponse interface.
 */
export function instanceOfPartnerCreationResponse(value: object): value is PartnerCreationResponse {
    return true;
}

export function PartnerCreationResponseFromJSON(json: any): PartnerCreationResponse {
    return PartnerCreationResponseFromJSONTyped(json, false);
}

export function PartnerCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'partner': json['partner'] == null ? undefined : PartnerDetailsResponseFromJSON(json['partner']),
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(PartnerUserDetailsResponseFromJSON)),
    };
}

export function PartnerCreationResponseToJSON(json: any): PartnerCreationResponse {
    return PartnerCreationResponseToJSONTyped(json, false);
}

export function PartnerCreationResponseToJSONTyped(value?: PartnerCreationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'partner': PartnerDetailsResponseToJSON(value['partner']),
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(PartnerUserDetailsResponseToJSON)),
    };
}

