/* tslint:disable */
/* eslint-disable */
/**
 * amazon-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountVerificationRequest
 */
export interface AccountVerificationRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountVerificationRequest
     */
    sortCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountVerificationRequest
     */
    accountNumber?: string;
}

/**
 * Check if a given object implements the AccountVerificationRequest interface.
 */
export function instanceOfAccountVerificationRequest(value: object): value is AccountVerificationRequest {
    return true;
}

export function AccountVerificationRequestFromJSON(json: any): AccountVerificationRequest {
    return AccountVerificationRequestFromJSONTyped(json, false);
}

export function AccountVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sortCode': json['sortCode'] == null ? undefined : json['sortCode'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
    };
}

export function AccountVerificationRequestToJSON(json: any): AccountVerificationRequest {
    return AccountVerificationRequestToJSONTyped(json, false);
}

export function AccountVerificationRequestToJSONTyped(value?: AccountVerificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortCode': value['sortCode'],
        'accountNumber': value['accountNumber'],
    };
}

