/* tslint:disable */
/* eslint-disable */
/**
 * amazon-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountVerificationResponse
 */
export interface AccountVerificationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AccountVerificationResponse
     */
    result?: boolean;
}

/**
 * Check if a given object implements the AccountVerificationResponse interface.
 */
export function instanceOfAccountVerificationResponse(value: object): value is AccountVerificationResponse {
    return true;
}

export function AccountVerificationResponseFromJSON(json: any): AccountVerificationResponse {
    return AccountVerificationResponseFromJSONTyped(json, false);
}

export function AccountVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function AccountVerificationResponseToJSON(json: any): AccountVerificationResponse {
    return AccountVerificationResponseToJSONTyped(json, false);
}

export function AccountVerificationResponseToJSONTyped(value?: AccountVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

