/* tslint:disable */
/* eslint-disable */
/**
 * amazon-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepaymentDTO } from './RepaymentDTO';
import {
    RepaymentDTOFromJSON,
    RepaymentDTOFromJSONTyped,
    RepaymentDTOToJSON,
    RepaymentDTOToJSONTyped,
} from './RepaymentDTO';

/**
 * 
 * @export
 * @interface RepaymentScheduleCreatedDTO
 */
export interface RepaymentScheduleCreatedDTO {
    /**
     * 
     * @type {string}
     * @memberof RepaymentScheduleCreatedDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RepaymentScheduleCreatedDTO
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof RepaymentScheduleCreatedDTO
     */
    agreementId?: string;
    /**
     * 
     * @type {Array<RepaymentDTO>}
     * @memberof RepaymentScheduleCreatedDTO
     */
    repayments?: Array<RepaymentDTO>;
}

/**
 * Check if a given object implements the RepaymentScheduleCreatedDTO interface.
 */
export function instanceOfRepaymentScheduleCreatedDTO(value: object): value is RepaymentScheduleCreatedDTO {
    return true;
}

export function RepaymentScheduleCreatedDTOFromJSON(json: any): RepaymentScheduleCreatedDTO {
    return RepaymentScheduleCreatedDTOFromJSONTyped(json, false);
}

export function RepaymentScheduleCreatedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepaymentScheduleCreatedDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'agreementId': json['agreementId'] == null ? undefined : json['agreementId'],
        'repayments': json['repayments'] == null ? undefined : ((json['repayments'] as Array<any>).map(RepaymentDTOFromJSON)),
    };
}

export function RepaymentScheduleCreatedDTOToJSON(json: any): RepaymentScheduleCreatedDTO {
    return RepaymentScheduleCreatedDTOToJSONTyped(json, false);
}

export function RepaymentScheduleCreatedDTOToJSONTyped(value?: RepaymentScheduleCreatedDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organisationId': value['organisationId'],
        'agreementId': value['agreementId'],
        'repayments': value['repayments'] == null ? undefined : ((value['repayments'] as Array<any>).map(RepaymentDTOToJSON)),
    };
}

