/* tslint:disable */
/* eslint-disable */
/**
 * api-loan-operations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    iban?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    sortCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    swiftBic?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    blz?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    accountHolderName?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    connectionId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    deleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    mask?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    tan?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    verified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    personal?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    partnerVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    mandateVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    verifiedForPayments?: boolean;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'iban': json['iban'] == null ? undefined : json['iban'],
        'number': json['number'] == null ? undefined : json['number'],
        'sortCode': json['sortCode'] == null ? undefined : json['sortCode'],
        'swiftBic': json['swiftBic'] == null ? undefined : json['swiftBic'],
        'blz': json['blz'] == null ? undefined : json['blz'],
        'country': json['country'] == null ? undefined : json['country'],
        'accountHolderName': json['accountHolderName'] == null ? undefined : json['accountHolderName'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
        'description': json['description'] == null ? undefined : json['description'],
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'connectionId': json['connectionId'] == null ? undefined : json['connectionId'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'mask': json['mask'] == null ? undefined : json['mask'],
        'tan': json['tan'] == null ? undefined : json['tan'],
        'verified': json['verified'] == null ? undefined : json['verified'],
        'personal': json['personal'] == null ? undefined : json['personal'],
        'partnerVerified': json['partnerVerified'] == null ? undefined : json['partnerVerified'],
        'mandateVerified': json['mandateVerified'] == null ? undefined : json['mandateVerified'],
        'verifiedForPayments': json['verifiedForPayments'] == null ? undefined : json['verifiedForPayments'],
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'iban': value['iban'],
        'number': value['number'],
        'sortCode': value['sortCode'],
        'swiftBic': value['swiftBic'],
        'blz': value['blz'],
        'country': value['country'],
        'accountHolderName': value['accountHolderName'],
        'currency': value['currency'],
        'bankName': value['bankName'],
        'description': value['description'],
        'organisationId': value['organisationId'],
        'connectionId': value['connectionId'],
        'deleted': value['deleted'],
        'externalId': value['externalId'],
        'mask': value['mask'],
        'tan': value['tan'],
        'verified': value['verified'],
        'personal': value['personal'],
        'partnerVerified': value['partnerVerified'],
        'mandateVerified': value['mandateVerified'],
        'verifiedForPayments': value['verifiedForPayments'],
    };
}

