/* tslint:disable */
/* eslint-disable */
/**
 * api-loan-operations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Disbursement
 */
export interface Disbursement {
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    agreementId?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    status?: DisbursementStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Disbursement
     */
    executionDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Disbursement
     */
    creationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    toAccountId?: string;
    /**
     * 
     * @type {number}
     * @memberof Disbursement
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    type?: DisbursementTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Disbursement
     */
    local?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Disbursement
     */
    accountVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    paymentType?: DisbursementPaymentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    walletType?: DisbursementWalletTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Disbursement
     */
    idempotencyKey?: string;
}


/**
 * @export
 */
export const DisbursementStatusEnum = {
    Rejected: 'REJECTED',
    Paid: 'PAID',
    Canceled: 'CANCELED',
    Failed: 'FAILED',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    WaitingForApproval: 'WAITING_FOR_APPROVAL'
} as const;
export type DisbursementStatusEnum = typeof DisbursementStatusEnum[keyof typeof DisbursementStatusEnum];

/**
 * @export
 */
export const DisbursementTypeEnum = {
    Automatic: 'AUTOMATIC',
    Manual: 'MANUAL'
} as const;
export type DisbursementTypeEnum = typeof DisbursementTypeEnum[keyof typeof DisbursementTypeEnum];

/**
 * @export
 */
export const DisbursementPaymentTypeEnum = {
    Disbursement: 'DISBURSEMENT',
    Refund: 'REFUND',
    InternalTransfer: 'INTERNAL_TRANSFER',
    Unknown: 'UNKNOWN'
} as const;
export type DisbursementPaymentTypeEnum = typeof DisbursementPaymentTypeEnum[keyof typeof DisbursementPaymentTypeEnum];

/**
 * @export
 */
export const DisbursementWalletTypeEnum = {
    InterestRateLoc: 'INTEREST_RATE_LOC',
    FixedFeeProducts: 'FIXED_FEE_PRODUCTS',
    InternalTransfers: 'INTERNAL_TRANSFERS',
    Unknown: 'UNKNOWN'
} as const;
export type DisbursementWalletTypeEnum = typeof DisbursementWalletTypeEnum[keyof typeof DisbursementWalletTypeEnum];


/**
 * Check if a given object implements the Disbursement interface.
 */
export function instanceOfDisbursement(value: object): value is Disbursement {
    return true;
}

export function DisbursementFromJSON(json: any): Disbursement {
    return DisbursementFromJSONTyped(json, false);
}

export function DisbursementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Disbursement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'agreementId': json['agreementId'] == null ? undefined : json['agreementId'],
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'executionDate': json['executionDate'] == null ? undefined : (new Date(json['executionDate'])),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'toAccountId': json['toAccountId'] == null ? undefined : json['toAccountId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'type': json['type'] == null ? undefined : json['type'],
        'local': json['local'] == null ? undefined : json['local'],
        'accountVerified': json['accountVerified'] == null ? undefined : json['accountVerified'],
        'paymentType': json['paymentType'] == null ? undefined : json['paymentType'],
        'walletType': json['walletType'] == null ? undefined : json['walletType'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
    };
}

export function DisbursementToJSON(json: any): Disbursement {
    return DisbursementToJSONTyped(json, false);
}

export function DisbursementToJSONTyped(value?: Disbursement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'agreementId': value['agreementId'],
        'organisationId': value['organisationId'],
        'status': value['status'],
        'executionDate': value['executionDate'] == null ? undefined : ((value['executionDate']).toISOString()),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
        'toAccountId': value['toAccountId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'type': value['type'],
        'local': value['local'],
        'accountVerified': value['accountVerified'],
        'paymentType': value['paymentType'],
        'walletType': value['walletType'],
        'idempotencyKey': value['idempotencyKey'],
    };
}

