/* tslint:disable */
/* eslint-disable */
/**
 * api-kyc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkDTO
 */
export interface LinkDTO {
    /**
     * 
     * @type {string}
     * @memberof LinkDTO
     */
    fullLink?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkDTO
     */
    uuid?: string;
}

/**
 * Check if a given object implements the LinkDTO interface.
 */
export function instanceOfLinkDTO(value: object): value is LinkDTO {
    return true;
}

export function LinkDTOFromJSON(json: any): LinkDTO {
    return LinkDTOFromJSONTyped(json, false);
}

export function LinkDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'fullLink': json['fullLink'] == null ? undefined : json['fullLink'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function LinkDTOToJSON(value?: LinkDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fullLink': value['fullLink'],
        'uuid': value['uuid'],
    };
}

