/* tslint:disable */
/* eslint-disable */
/**
 * api-loan-operations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CashTransferRequestDTO,
  Disbursement,
  ErrorMessageDTO,
} from '../models/index';
import {
    CashTransferRequestDTOFromJSON,
    CashTransferRequestDTOToJSON,
    DisbursementFromJSON,
    DisbursementToJSON,
    ErrorMessageDTOFromJSON,
    ErrorMessageDTOToJSON,
} from '../models/index';

export interface AbortDisbursementRequest {
    disbursementId: string;
    xXORGID: string;
}

export interface ApproveDisbursementRequest {
    disbursementId: string;
    xXORGID: string;
}

export interface CreateDisbursementRequest {
    xXORGID: string;
    cashTransferRequestDTO: CashTransferRequestDTO;
}

export interface ExecuteDisbursementRequest {
    disbursementId: string;
    xXORGID: string;
}

export interface GetDisbursementsRequest {
    xXORGID: string;
    agreementId?: string;
    dateFrom?: string;
    dateTo?: string;
    status?: Array<GetDisbursementsStatusEnum>;
}

export interface RejectDisbursementRequest {
    disbursementId: string;
    xXORGID: string;
}

/**
 * 
 */
export class DisbursementsControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async abortDisbursementRaw(requestParameters: AbortDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['disbursementId'] == null) {
            throw new runtime.RequiredError(
                'disbursementId',
                'Required parameter "disbursementId" was null or undefined when calling abortDisbursement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling abortDisbursement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['disbursementId'] != null) {
            queryParameters['disbursementId'] = requestParameters['disbursementId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements/abort`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async abortDisbursement(requestParameters: AbortDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.abortDisbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **ORGROLE[SELF][cashPaymentApprover]** role.
     */
    async approveDisbursementRaw(requestParameters: ApproveDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['disbursementId'] == null) {
            throw new runtime.RequiredError(
                'disbursementId',
                'Required parameter "disbursementId" was null or undefined when calling approveDisbursement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling approveDisbursement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['disbursementId'] != null) {
            queryParameters['disbursementId'] = requestParameters['disbursementId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements/approve`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **ORGROLE[SELF][cashPaymentApprover]** role.
     */
    async approveDisbursement(requestParameters: ApproveDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.approveDisbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async createDisbursementRaw(requestParameters: CreateDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createDisbursement().'
            );
        }

        if (requestParameters['cashTransferRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'cashTransferRequestDTO',
                'Required parameter "cashTransferRequestDTO" was null or undefined when calling createDisbursement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CashTransferRequestDTOToJSON(requestParameters['cashTransferRequestDTO']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async createDisbursement(requestParameters: CreateDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createDisbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **ORGROLE[SELF][admin]** role.
     */
    async executeDisbursementRaw(requestParameters: ExecuteDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['disbursementId'] == null) {
            throw new runtime.RequiredError(
                'disbursementId',
                'Required parameter "disbursementId" was null or undefined when calling executeDisbursement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling executeDisbursement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['disbursementId'] != null) {
            queryParameters['disbursementId'] = requestParameters['disbursementId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements/execute`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * This API requires **ORGROLE[SELF][admin]** role.
     */
    async executeDisbursement(requestParameters: ExecuteDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.executeDisbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getDisbursementsRaw(requestParameters: GetDisbursementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Disbursement>>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getDisbursements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agreementId'] != null) {
            queryParameters['agreementId'] = requestParameters['agreementId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['dateFrom'] = requestParameters['dateFrom'];
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['dateTo'] = requestParameters['dateTo'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DisbursementFromJSON));
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getDisbursements(requestParameters: GetDisbursementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Disbursement>> {
        const response = await this.getDisbursementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **ORGROLE[SELF][admin]** role.
     */
    async rejectDisbursementRaw(requestParameters: RejectDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['disbursementId'] == null) {
            throw new runtime.RequiredError(
                'disbursementId',
                'Required parameter "disbursementId" was null or undefined when calling rejectDisbursement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling rejectDisbursement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['disbursementId'] != null) {
            queryParameters['disbursementId'] = requestParameters['disbursementId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/disbursements/reject`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **ORGROLE[SELF][admin]** role.
     */
    async rejectDisbursement(requestParameters: RejectDisbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.rejectDisbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetDisbursementsStatusEnum = {
    Rejected: 'REJECTED',
    Paid: 'PAID',
    Canceled: 'CANCELED',
    Failed: 'FAILED',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    WaitingForApproval: 'WAITING_FOR_APPROVAL'
} as const;
export type GetDisbursementsStatusEnum = typeof GetDisbursementsStatusEnum[keyof typeof GetDisbursementsStatusEnum];
