/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdditionalFeeCancelRequest,
  AdditionalFeeExecuteRequest,
  AdditionalFeeExternalDisputeCreateRequest,
  AdditionalFeeInternalAgreementCreateRequest,
} from '../models/index';
import {
    AdditionalFeeCancelRequestFromJSON,
    AdditionalFeeCancelRequestToJSON,
    AdditionalFeeExecuteRequestFromJSON,
    AdditionalFeeExecuteRequestToJSON,
    AdditionalFeeExternalDisputeCreateRequestFromJSON,
    AdditionalFeeExternalDisputeCreateRequestToJSON,
    AdditionalFeeInternalAgreementCreateRequestFromJSON,
    AdditionalFeeInternalAgreementCreateRequestToJSON,
} from '../models/index';

export interface CancelRequest {
    id: string;
    xXORGID: string;
    additionalFeeCancelRequest: AdditionalFeeCancelRequest;
    xxApiVersion?: CancelXxApiVersionEnum;
}

export interface ExecuteRequest {
    id: string;
    xXORGID: string;
    additionalFeeExecuteRequest: AdditionalFeeExecuteRequest;
}

export interface Get1Request {
    xXORGID: string;
}

export interface PostExternalDisputeRequest {
    xXORGID: string;
    additionalFeeExternalDisputeCreateRequest: AdditionalFeeExternalDisputeCreateRequest;
}

export interface PostInternalAgreementRequest {
    xXORGID: string;
    additionalFeeInternalAgreementCreateRequest: AdditionalFeeInternalAgreementCreateRequest;
}

/**
 * 
 */
export class AdditionalFeeControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     * @deprecated
     */
    async cancelRaw(requestParameters: CancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancel().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling cancel().'
            );
        }

        if (requestParameters['additionalFeeCancelRequest'] == null) {
            throw new runtime.RequiredError(
                'additionalFeeCancelRequest',
                'Required parameter "additionalFeeCancelRequest" was null or undefined when calling cancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xxApiVersion'] != null) {
            headerParameters['xx-api-version'] = String(requestParameters['xxApiVersion']);
        }

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/additional-fee/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AdditionalFeeCancelRequestToJSON(requestParameters['additionalFeeCancelRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     * @deprecated
     */
    async cancel(requestParameters: CancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.cancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **ORGROLE[SELF][agreementApprover]** role.
     */
    async executeRaw(requestParameters: ExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling execute().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling execute().'
            );
        }

        if (requestParameters['additionalFeeExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'additionalFeeExecuteRequest',
                'Required parameter "additionalFeeExecuteRequest" was null or undefined when calling execute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/additional-fee/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AdditionalFeeExecuteRequestToJSON(requestParameters['additionalFeeExecuteRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **ORGROLE[SELF][agreementApprover]** role.
     */
    async execute(requestParameters: ExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.executeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async get1Raw(requestParameters: Get1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling get1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/additional-fee`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async get1(requestParameters: Get1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.get1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async postExternalDisputeRaw(requestParameters: PostExternalDisputeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling postExternalDispute().'
            );
        }

        if (requestParameters['additionalFeeExternalDisputeCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'additionalFeeExternalDisputeCreateRequest',
                'Required parameter "additionalFeeExternalDisputeCreateRequest" was null or undefined when calling postExternalDispute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/additional-fee/external-dispute`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdditionalFeeExternalDisputeCreateRequestToJSON(requestParameters['additionalFeeExternalDisputeCreateRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async postExternalDispute(requestParameters: PostExternalDisputeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postExternalDisputeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async postInternalAgreementRaw(requestParameters: PostInternalAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling postInternalAgreement().'
            );
        }

        if (requestParameters['additionalFeeInternalAgreementCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'additionalFeeInternalAgreementCreateRequest',
                'Required parameter "additionalFeeInternalAgreementCreateRequest" was null or undefined when calling postInternalAgreement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/additional-fee/internal-agreement`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdditionalFeeInternalAgreementCreateRequestToJSON(requestParameters['additionalFeeInternalAgreementCreateRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async postInternalAgreement(requestParameters: PostInternalAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postInternalAgreementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CancelXxApiVersionEnum = {
    _2: '2'
} as const;
export type CancelXxApiVersionEnum = typeof CancelXxApiVersionEnum[keyof typeof CancelXxApiVersionEnum];
