/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DelinquencyAgreementStatusResponse,
} from '../models/index';
import {
    DelinquencyAgreementStatusResponseFromJSON,
    DelinquencyAgreementStatusResponseToJSON,
} from '../models/index';

export interface LatestDelinquencyStatusEntryForEachAgreementRequest {
    orgId: Array<string>;
    xXORGID: string;
}

/**
 * 
 */
export class AgreementDelinquencyStatusControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     */
    async latestDelinquencyStatusEntryForEachAgreementRaw(requestParameters: LatestDelinquencyStatusEntryForEachAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DelinquencyAgreementStatusResponse>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling latestDelinquencyStatusEntryForEachAgreement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling latestDelinquencyStatusEntryForEachAgreement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/delinquency-status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DelinquencyAgreementStatusResponseFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async latestDelinquencyStatusEntryForEachAgreement(requestParameters: LatestDelinquencyStatusEntryForEachAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DelinquencyAgreementStatusResponse>> {
        const response = await this.latestDelinquencyStatusEntryForEachAgreementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
