/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetCsvPurchasesStatementForAgreementRequest {
    outputFormat: GetCsvPurchasesStatementForAgreementOutputFormatEnum;
    agreementId: string;
    xXORGID: string;
}

export interface GetCsvPurchasesStatementForOrganisationRequest {
    outputFormat: GetCsvPurchasesStatementForOrganisationOutputFormatEnum;
    xXORGID: string;
}

export interface GetCsvRepaymentsStatementForAgreementRequest {
    outputFormat: GetCsvRepaymentsStatementForAgreementOutputFormatEnum;
    agreementId: string;
    xXORGID: string;
}

export interface GetCsvRepaymentsStatementForOrganisationRequest {
    outputFormat: GetCsvRepaymentsStatementForOrganisationOutputFormatEnum;
    xXORGID: string;
}

export interface GetXlsStatementForOrganisationRequest {
    xXORGID: string;
}

/**
 * 
 */
export class StatementControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvPurchasesStatementForAgreementRaw(requestParameters: GetCsvPurchasesStatementForAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling getCsvPurchasesStatementForAgreement().'
            );
        }

        if (requestParameters['agreementId'] == null) {
            throw new runtime.RequiredError(
                'agreementId',
                'Required parameter "agreementId" was null or undefined when calling getCsvPurchasesStatementForAgreement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCsvPurchasesStatementForAgreement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['outputFormat'] != null) {
            headerParameters['output-format'] = String(requestParameters['outputFormat']);
        }

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/statement/purchases/{agreementId}`;
        urlPath = urlPath.replace(`{${"agreementId"}}`, encodeURIComponent(String(requestParameters['agreementId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvPurchasesStatementForAgreement(requestParameters: GetCsvPurchasesStatementForAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getCsvPurchasesStatementForAgreementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvPurchasesStatementForOrganisationRaw(requestParameters: GetCsvPurchasesStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling getCsvPurchasesStatementForOrganisation().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCsvPurchasesStatementForOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['outputFormat'] != null) {
            headerParameters['output-format'] = String(requestParameters['outputFormat']);
        }

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/statement/purchases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvPurchasesStatementForOrganisation(requestParameters: GetCsvPurchasesStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getCsvPurchasesStatementForOrganisationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvRepaymentsStatementForAgreementRaw(requestParameters: GetCsvRepaymentsStatementForAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling getCsvRepaymentsStatementForAgreement().'
            );
        }

        if (requestParameters['agreementId'] == null) {
            throw new runtime.RequiredError(
                'agreementId',
                'Required parameter "agreementId" was null or undefined when calling getCsvRepaymentsStatementForAgreement().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCsvRepaymentsStatementForAgreement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['outputFormat'] != null) {
            headerParameters['output-format'] = String(requestParameters['outputFormat']);
        }

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/statement/repayments/{agreementId}`;
        urlPath = urlPath.replace(`{${"agreementId"}}`, encodeURIComponent(String(requestParameters['agreementId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvRepaymentsStatementForAgreement(requestParameters: GetCsvRepaymentsStatementForAgreementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getCsvRepaymentsStatementForAgreementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvRepaymentsStatementForOrganisationRaw(requestParameters: GetCsvRepaymentsStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling getCsvRepaymentsStatementForOrganisation().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getCsvRepaymentsStatementForOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['outputFormat'] != null) {
            headerParameters['output-format'] = String(requestParameters['outputFormat']);
        }

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/statement/repayments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getCsvRepaymentsStatementForOrganisation(requestParameters: GetCsvRepaymentsStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getCsvRepaymentsStatementForOrganisationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getXlsStatementForOrganisationRaw(requestParameters: GetXlsStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getXlsStatementForOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/statement`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getXlsStatementForOrganisation(requestParameters: GetXlsStatementForOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getXlsStatementForOrganisationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCsvPurchasesStatementForAgreementOutputFormatEnum = {
    Csv: 'CSV'
} as const;
export type GetCsvPurchasesStatementForAgreementOutputFormatEnum = typeof GetCsvPurchasesStatementForAgreementOutputFormatEnum[keyof typeof GetCsvPurchasesStatementForAgreementOutputFormatEnum];
/**
 * @export
 */
export const GetCsvPurchasesStatementForOrganisationOutputFormatEnum = {
    Csv: 'CSV'
} as const;
export type GetCsvPurchasesStatementForOrganisationOutputFormatEnum = typeof GetCsvPurchasesStatementForOrganisationOutputFormatEnum[keyof typeof GetCsvPurchasesStatementForOrganisationOutputFormatEnum];
/**
 * @export
 */
export const GetCsvRepaymentsStatementForAgreementOutputFormatEnum = {
    Csv: 'CSV'
} as const;
export type GetCsvRepaymentsStatementForAgreementOutputFormatEnum = typeof GetCsvRepaymentsStatementForAgreementOutputFormatEnum[keyof typeof GetCsvRepaymentsStatementForAgreementOutputFormatEnum];
/**
 * @export
 */
export const GetCsvRepaymentsStatementForOrganisationOutputFormatEnum = {
    Csv: 'CSV'
} as const;
export type GetCsvRepaymentsStatementForOrganisationOutputFormatEnum = typeof GetCsvRepaymentsStatementForOrganisationOutputFormatEnum[keyof typeof GetCsvRepaymentsStatementForOrganisationOutputFormatEnum];
