/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageModelTransaction,
  TransactionDetails,
} from '../models/index';
import {
    PageModelTransactionFromJSON,
    PageModelTransactionToJSON,
    TransactionDetailsFromJSON,
    TransactionDetailsToJSON,
} from '../models/index';

export interface GetAllTransactionsRequest {
    xXORGID: string;
    page?: number;
    size?: number;
    accountId?: string;
    statuses?: Set<GetAllTransactionsStatusesEnum>;
    executionTypes?: Set<GetAllTransactionsExecutionTypesEnum>;
    transactionTypes?: Set<GetAllTransactionsTransactionTypesEnum>;
}

export interface GetTransactionByIdRequest {
    accountId: string;
    transactionId: string;
    xXORGID: string;
}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getAllTransactionsRaw(requestParameters: GetAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageModelTransaction>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getAllTransactions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['statuses'] != null) {
            queryParameters['statuses'] = requestParameters['statuses'];
        }

        if (requestParameters['executionTypes'] != null) {
            queryParameters['executionTypes'] = requestParameters['executionTypes'];
        }

        if (requestParameters['transactionTypes'] != null) {
            queryParameters['transactionTypes'] = requestParameters['transactionTypes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ui-transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageModelTransactionFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getAllTransactions(requestParameters: GetAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageModelTransaction> {
        const response = await this.getAllTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getTransactionByIdRaw(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDetails>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getTransactionById().'
            );
        }

        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getTransactionById().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getTransactionById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ui-transactions/{accountId}/{transactionId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDetailsFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **ORGROLE[+#organisationId+][admin]** role.
     */
    async getTransactionById(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDetails> {
        const response = await this.getTransactionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAllTransactionsStatusesEnum = {
    Sent: 'SENT',
    Received: 'RECEIVED',
    Pending: 'PENDING',
    Retrying: 'RETRYING',
    Failed: 'FAILED',
    Canceled: 'CANCELED',
    Completed: 'COMPLETED',
    Reversal: 'REVERSAL',
    Refund: 'REFUND',
    Unknown: 'UNKNOWN',
    PartiallyPaid: 'PARTIALLY_PAID'
} as const;
export type GetAllTransactionsStatusesEnum = typeof GetAllTransactionsStatusesEnum[keyof typeof GetAllTransactionsStatusesEnum];
/**
 * @export
 */
export const GetAllTransactionsExecutionTypesEnum = {
    Scheduled: 'SCHEDULED',
    Executed: 'EXECUTED'
} as const;
export type GetAllTransactionsExecutionTypesEnum = typeof GetAllTransactionsExecutionTypesEnum[keyof typeof GetAllTransactionsExecutionTypesEnum];
/**
 * @export
 */
export const GetAllTransactionsTransactionTypesEnum = {
    Invoice: 'INVOICE',
    Card: 'CARD',
    Cash: 'CASH',
    Refund: 'REFUND',
    Repayment: 'REPAYMENT',
    Collection: 'COLLECTION'
} as const;
export type GetAllTransactionsTransactionTypesEnum = typeof GetAllTransactionsTransactionTypesEnum[keyof typeof GetAllTransactionsTransactionTypesEnum];
