/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageModelBalanceSheetData } from './PageModelBalanceSheetData';
import {
    PageModelBalanceSheetDataFromJSON,
    PageModelBalanceSheetDataFromJSONTyped,
    PageModelBalanceSheetDataToJSON,
    PageModelBalanceSheetDataToJSONTyped,
} from './PageModelBalanceSheetData';

/**
 * 
 * @export
 * @interface BalanceSheetResponse
 */
export interface BalanceSheetResponse {
    /**
     * 
     * @type {string}
     * @memberof BalanceSheetResponse
     */
    type?: BalanceSheetResponseTypeEnum;
    /**
     * 
     * @type {PageModelBalanceSheetData}
     * @memberof BalanceSheetResponse
     */
    data?: PageModelBalanceSheetData;
}


/**
 * @export
 */
export const BalanceSheetResponseTypeEnum = {
    BalanceSheet: 'BALANCE_SHEET',
    ProfitAndLoss: 'PROFIT_AND_LOSS',
    TransactionsUnconfirmed: 'TRANSACTIONS_UNCONFIRMED',
    TransactionsConfirmed: 'TRANSACTIONS_CONFIRMED'
} as const;
export type BalanceSheetResponseTypeEnum = typeof BalanceSheetResponseTypeEnum[keyof typeof BalanceSheetResponseTypeEnum];


/**
 * Check if a given object implements the BalanceSheetResponse interface.
 */
export function instanceOfBalanceSheetResponse(value: object): value is BalanceSheetResponse {
    return true;
}

export function BalanceSheetResponseFromJSON(json: any): BalanceSheetResponse {
    return BalanceSheetResponseFromJSONTyped(json, false);
}

export function BalanceSheetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceSheetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'data': json['data'] == null ? undefined : PageModelBalanceSheetDataFromJSON(json['data']),
    };
}

export function BalanceSheetResponseToJSON(json: any): BalanceSheetResponse {
    return BalanceSheetResponseToJSONTyped(json, false);
}

export function BalanceSheetResponseToJSONTyped(value?: BalanceSheetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': PageModelBalanceSheetDataToJSON(value['data']),
    };
}

