/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDetails } from './UserDetails';
import {
    UserDetailsFromJSON,
    UserDetailsFromJSONTyped,
    UserDetailsToJSON,
    UserDetailsToJSONTyped,
} from './UserDetails';
import type { AnalysisDataSnapshotDetails } from './AnalysisDataSnapshotDetails';
import {
    AnalysisDataSnapshotDetailsFromJSON,
    AnalysisDataSnapshotDetailsFromJSONTyped,
    AnalysisDataSnapshotDetailsToJSON,
    AnalysisDataSnapshotDetailsToJSONTyped,
} from './AnalysisDataSnapshotDetails';

/**
 * 
 * @export
 * @interface CheckWithTypeDetails
 */
export interface CheckWithTypeDetails {
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    resourceValue?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckWithTypeDetails
     */
    status?: CheckWithTypeDetailsStatusEnum;
    /**
     * 
     * @type {Set<string>}
     * @memberof CheckWithTypeDetails
     */
    availableManualMarks?: Set<CheckWithTypeDetailsAvailableManualMarksEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckWithTypeDetails
     */
    analysisDataTypes?: Array<CheckWithTypeDetailsAnalysisDataTypesEnum>;
    /**
     * 
     * @type {Array<AnalysisDataSnapshotDetails>}
     * @memberof CheckWithTypeDetails
     */
    analysisDataSnapshots?: Array<AnalysisDataSnapshotDetails>;
    /**
     * 
     * @type {UserDetails}
     * @memberof CheckWithTypeDetails
     */
    checkedBy?: UserDetails;
    /**
     * 
     * @type {Date}
     * @memberof CheckWithTypeDetails
     */
    checkedOn?: Date;
}


/**
 * @export
 */
export const CheckWithTypeDetailsStatusEnum = {
    Pending: 'PENDING',
    Completed: 'COMPLETED',
    Warning: 'WARNING',
    Failed: 'FAILED'
} as const;
export type CheckWithTypeDetailsStatusEnum = typeof CheckWithTypeDetailsStatusEnum[keyof typeof CheckWithTypeDetailsStatusEnum];

/**
 * @export
 */
export const CheckWithTypeDetailsAvailableManualMarksEnum = {
    Completed: 'COMPLETED',
    Warning: 'WARNING',
    Failed: 'FAILED'
} as const;
export type CheckWithTypeDetailsAvailableManualMarksEnum = typeof CheckWithTypeDetailsAvailableManualMarksEnum[keyof typeof CheckWithTypeDetailsAvailableManualMarksEnum];

/**
 * @export
 */
export const CheckWithTypeDetailsAnalysisDataTypesEnum = {
    RevenueVsEbitdaTimeSeries: 'REVENUE_VS_EBITDA_TIME_SERIES',
    CashBalanceTimeSeries: 'CASH_BALANCE_TIME_SERIES',
    DebtTimeSeries: 'DEBT_TIME_SERIES',
    AssetsLiabilitiesRatioTimeSeries: 'ASSETS_LIABILITIES_RATIO_TIME_SERIES',
    AmazonMonthlyNetRevenueBySourceSeries: 'AMAZON_MONTHLY_NET_REVENUE_BY_SOURCE_SERIES',
    AmazonRevenueByFulfillmentChannel: 'AMAZON_REVENUE_BY_FULFILLMENT_CHANNEL',
    AmazonRevenueRunRateDaily: 'AMAZON_REVENUE_RUN_RATE_DAILY',
    AmazonCashBankBalance: 'AMAZON_CASH_BANK_BALANCE',
    AmazonCashUnreconciledTransfers: 'AMAZON_CASH_UNRECONCILED_TRANSFERS',
    HeronMissingAccounts: 'HERON_MISSING_ACCOUNTS',
    AmazonDebtUncappedBalance: 'AMAZON_DEBT_UNCAPPED_BALANCE',
    AmazonDebtHeronCashFlows: 'AMAZON_DEBT_HERON_CASH_FLOWS',
    AmazonDebtExistingDebt: 'AMAZON_DEBT_EXISTING_DEBT',
    AmazonAssetsInventoryValuation: 'AMAZON_ASSETS_INVENTORY_VALUATION',
    AmazonAssetsNetEstimate: 'AMAZON_ASSETS_NET_ESTIMATE',
    AmazonBehaviourAccountStatusVsRevenue: 'AMAZON_BEHAVIOUR_ACCOUNT_STATUS_VS_REVENUE',
    AmazonBehaviourTopBrands: 'AMAZON_BEHAVIOUR_TOP_BRANDS',
    AmazonBehaviourAsinsByDomain: 'AMAZON_BEHAVIOUR_ASINS_BY_DOMAIN',
    AmazonRevenueDaily: 'AMAZON_REVENUE_DAILY',
    AmazonAssetsAsinPerformance: 'AMAZON_ASSETS_ASIN_PERFORMANCE',
    AmazonTax: 'AMAZON_TAX',
    AmazonAssetsRunway: 'AMAZON_ASSETS_RUNWAY',
    AmazonAssetsInventoryValuationInbound: 'AMAZON_ASSETS_INVENTORY_VALUATION_INBOUND',
    AmazonAssetsNetAssetsEstimateInbound: 'AMAZON_ASSETS_NET_ASSETS_ESTIMATE_INBOUND',
    AmazonDebtHeronByMerchant: 'AMAZON_DEBT_HERON_BY_MERCHANT',
    AmazonGeneralStorefrontUrl: 'AMAZON_GENERAL_STOREFRONT_URL',
    AmazonGeneralAsinUrl: 'AMAZON_GENERAL_ASIN_URL',
    AmazonGeneralSellerFlag: 'AMAZON_GENERAL_SELLER_FLAG',
    AmazonRevenueByProductCategory: 'AMAZON_REVENUE_BY_PRODUCT_CATEGORY',
    AmazonCashAccountLevelReserve: 'AMAZON_CASH_ACCOUNT_LEVEL_RESERVE',
    AmazonCashOperatingCashFlow: 'AMAZON_CASH_OPERATING_CASH_FLOW',
    AmazonBehaviourMarketplacePercentageRevenues: 'AMAZON_BEHAVIOUR_MARKETPLACE_PERCENTAGE_REVENUES',
    AmazonBehaviourAccountStatus: 'AMAZON_BEHAVIOUR_ACCOUNT_STATUS',
    AmazonAssetsAsinAvgPrice: 'AMAZON_ASSETS_ASIN_AVG_PRICE',
    AmazonAssetsRevenueByAsin: 'AMAZON_ASSETS_REVENUE_BY_ASIN',
    AmazonMarketingRoas: 'AMAZON_MARKETING_ROAS',
    AmazonMarketingAdSpendVsRevenueCorrelation: 'AMAZON_MARKETING_AD_SPEND_VS_REVENUE_CORRELATION',
    AmazonMarketingAdSpend: 'AMAZON_MARKETING_AD_SPEND',
    AmazonRevenueDisbursementsVsCash: 'AMAZON_REVENUE_DISBURSEMENTS_VS_CASH',
    AmazonRevenueGrossVsDisbursements: 'AMAZON_REVENUE_GROSS_VS_DISBURSEMENTS',
    AmazonRevenueReturns: 'AMAZON_REVENUE_RETURNS',
    AmazonDebtHeronFlowsByMerchant: 'AMAZON_DEBT_HERON_FLOWS_BY_MERCHANT',
    AmazonBehaviourReturns: 'AMAZON_BEHAVIOUR_RETURNS',
    AmazonBankKeyHeronTransactions: 'AMAZON_BANK_KEY_HERON_TRANSACTIONS',
    AmazonDebtKeyHeronTransactions: 'AMAZON_DEBT_KEY_HERON_TRANSACTIONS',
    AmazonBankCashOutflows: 'AMAZON_BANK_CASH_OUTFLOWS',
    AmazonBankCashInflows: 'AMAZON_BANK_CASH_INFLOWS',
    AmazonInventoryNetProceedsBalance: 'AMAZON_INVENTORY_NET_PROCEEDS_BALANCE',
    AmazonIncomeProfitabilityDirectSellingFeesPerc: 'AMAZON_INCOME_PROFITABILITY_DIRECT_SELLING_FEES_PERC',
    AmazonIncomeProfitabilityGrossVsDisbursement: 'AMAZON_INCOME_PROFITABILITY_GROSS_VS_DISBURSEMENT',
    AmazonBehaviourAccountHealthFlags: 'AMAZON_BEHAVIOUR_ACCOUNT_HEALTH_FLAGS',
    AmazonMarketingAdSpendVsRoas: 'AMAZON_MARKETING_AD_SPEND_VS_ROAS',
    AmazonBankHeronCategorisationConfidenceNsfFeeProbability: 'AMAZON_BANK_HERON_CATEGORISATION_CONFIDENCE_NSF_FEE_PROBABILITY',
    AutomaticDecision: 'AUTOMATIC_DECISION'
} as const;
export type CheckWithTypeDetailsAnalysisDataTypesEnum = typeof CheckWithTypeDetailsAnalysisDataTypesEnum[keyof typeof CheckWithTypeDetailsAnalysisDataTypesEnum];


/**
 * Check if a given object implements the CheckWithTypeDetails interface.
 */
export function instanceOfCheckWithTypeDetails(value: object): value is CheckWithTypeDetails {
    return true;
}

export function CheckWithTypeDetailsFromJSON(json: any): CheckWithTypeDetails {
    return CheckWithTypeDetailsFromJSONTyped(json, false);
}

export function CheckWithTypeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckWithTypeDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'] == null ? undefined : json['group'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'resourceValue': json['resourceValue'] == null ? undefined : json['resourceValue'],
        'status': json['status'] == null ? undefined : json['status'],
        'availableManualMarks': json['availableManualMarks'] == null ? undefined : new Set(json['availableManualMarks']),
        'analysisDataTypes': json['analysisDataTypes'] == null ? undefined : json['analysisDataTypes'],
        'analysisDataSnapshots': json['analysisDataSnapshots'] == null ? undefined : ((json['analysisDataSnapshots'] as Array<any>).map(AnalysisDataSnapshotDetailsFromJSON)),
        'checkedBy': json['checkedBy'] == null ? undefined : UserDetailsFromJSON(json['checkedBy']),
        'checkedOn': json['checkedOn'] == null ? undefined : (new Date(json['checkedOn'])),
    };
}

export function CheckWithTypeDetailsToJSON(json: any): CheckWithTypeDetails {
    return CheckWithTypeDetailsToJSONTyped(json, false);
}

export function CheckWithTypeDetailsToJSONTyped(value?: CheckWithTypeDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'resourceValue': value['resourceValue'],
        'status': value['status'],
        'availableManualMarks': value['availableManualMarks'] == null ? undefined : Array.from(value['availableManualMarks'] as Set<any>),
        'analysisDataTypes': value['analysisDataTypes'],
        'analysisDataSnapshots': value['analysisDataSnapshots'] == null ? undefined : ((value['analysisDataSnapshots'] as Array<any>).map(AnalysisDataSnapshotDetailsToJSON)),
        'checkedBy': UserDetailsToJSON(value['checkedBy']),
        'checkedOn': value['checkedOn'] == null ? undefined : ((value['checkedOn']).toISOString()),
    };
}

