/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountPerStage } from './CountPerStage';
import {
    CountPerStageFromJSON,
    CountPerStageFromJSONTyped,
    CountPerStageToJSON,
    CountPerStageToJSONTyped,
} from './CountPerStage';

/**
 * 
 * @export
 * @interface DealsSummary
 */
export interface DealsSummary {
    /**
     * 
     * @type {Array<CountPerStage>}
     * @memberof DealsSummary
     */
    counts?: Array<CountPerStage>;
}

/**
 * Check if a given object implements the DealsSummary interface.
 */
export function instanceOfDealsSummary(value: object): value is DealsSummary {
    return true;
}

export function DealsSummaryFromJSON(json: any): DealsSummary {
    return DealsSummaryFromJSONTyped(json, false);
}

export function DealsSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealsSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'counts': json['counts'] == null ? undefined : ((json['counts'] as Array<any>).map(CountPerStageFromJSON)),
    };
}

export function DealsSummaryToJSON(json: any): DealsSummary {
    return DealsSummaryToJSONTyped(json, false);
}

export function DealsSummaryToJSONTyped(value?: DealsSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'counts': value['counts'] == null ? undefined : ((value['counts'] as Array<any>).map(CountPerStageToJSON)),
    };
}

