/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditableField
 */
export interface EditableField {
    /**
     * 
     * @type {string}
     * @memberof EditableField
     */
    value?: string;
    /**
     * 
     * @type {Date}
     * @memberof EditableField
     */
    modifiedAt?: Date;
}

/**
 * Check if a given object implements the EditableField interface.
 */
export function instanceOfEditableField(value: object): value is EditableField {
    return true;
}

export function EditableFieldFromJSON(json: any): EditableField {
    return EditableFieldFromJSONTyped(json, false);
}

export function EditableFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditableField {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
    };
}

export function EditableFieldToJSON(json: any): EditableField {
    return EditableFieldToJSONTyped(json, false);
}

export function EditableFieldToJSONTyped(value?: EditableField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
    };
}

