/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAmazonInventoryNetProceedsBalanceData200ResponseInner
 */
export interface GetAmazonInventoryNetProceedsBalanceData200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAmazonInventoryNetProceedsBalanceData200ResponseInner
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAmazonInventoryNetProceedsBalanceData200ResponseInner
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonInventoryNetProceedsBalanceData200ResponseInner
     */
    reserveBalanceGBP?: number;
}

/**
 * Check if a given object implements the GetAmazonInventoryNetProceedsBalanceData200ResponseInner interface.
 */
export function instanceOfGetAmazonInventoryNetProceedsBalanceData200ResponseInner(value: object): value is GetAmazonInventoryNetProceedsBalanceData200ResponseInner {
    return true;
}

export function GetAmazonInventoryNetProceedsBalanceData200ResponseInnerFromJSON(json: any): GetAmazonInventoryNetProceedsBalanceData200ResponseInner {
    return GetAmazonInventoryNetProceedsBalanceData200ResponseInnerFromJSONTyped(json, false);
}

export function GetAmazonInventoryNetProceedsBalanceData200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAmazonInventoryNetProceedsBalanceData200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'reserveBalanceGBP': json['reserveBalanceGBP'] == null ? undefined : json['reserveBalanceGBP'],
    };
}

export function GetAmazonInventoryNetProceedsBalanceData200ResponseInnerToJSON(json: any): GetAmazonInventoryNetProceedsBalanceData200ResponseInner {
    return GetAmazonInventoryNetProceedsBalanceData200ResponseInnerToJSONTyped(json, false);
}

export function GetAmazonInventoryNetProceedsBalanceData200ResponseInnerToJSONTyped(value?: GetAmazonInventoryNetProceedsBalanceData200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'currency': value['currency'],
        'reserveBalanceGBP': value['reserveBalanceGBP'],
    };
}

