/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
 */
export interface GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    discountedValue?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    cashBalanceGbp?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    disbursementToRevenueRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    loanBalanceGbp?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner
     */
    reserveBalanceGbp?: number;
}

/**
 * Check if a given object implements the GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner interface.
 */
export function instanceOfGetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner(value: object): value is GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner {
    return true;
}

export function GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerFromJSON(json: any): GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner {
    return GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerFromJSONTyped(json, false);
}

export function GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'discountedValue': json['discountedValue'] == null ? undefined : json['discountedValue'],
        'cashBalanceGbp': json['cashBalanceGbp'] == null ? undefined : json['cashBalanceGbp'],
        'disbursementToRevenueRatio': json['disbursementToRevenueRatio'] == null ? undefined : json['disbursementToRevenueRatio'],
        'loanBalanceGbp': json['loanBalanceGbp'] == null ? undefined : json['loanBalanceGbp'],
        'reserveBalanceGbp': json['reserveBalanceGbp'] == null ? undefined : json['reserveBalanceGbp'],
    };
}

export function GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerToJSON(json: any): GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner {
    return GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerToJSONTyped(json, false);
}

export function GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInnerToJSONTyped(value?: GetAmazonAssetsNetAssetsEstimateInboundData200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'discountedValue': value['discountedValue'],
        'cashBalanceGbp': value['cashBalanceGbp'],
        'disbursementToRevenueRatio': value['disbursementToRevenueRatio'],
        'loanBalanceGbp': value['loanBalanceGbp'],
        'reserveBalanceGbp': value['reserveBalanceGbp'],
    };
}

