/* tslint:disable */
/* eslint-disable */
/**
 * api-underwriting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScorecardResult
 */
export interface ScorecardResult {
    /**
     * 
     * @type {string}
     * @memberof ScorecardResult
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScorecardResult
     */
    dealId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScorecardResult
     */
    scorecardType?: ScorecardResultScorecardTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ScorecardResult
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof ScorecardResult
     */
    scorecardOutput?: string;
    /**
     * 
     * @type {Date}
     * @memberof ScorecardResult
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const ScorecardResultScorecardTypeEnum = {
    Banking: 'BANKING',
    BankingPlaidAssets: 'BANKING_PLAID_ASSETS',
    EquifaxCreditBureau: 'EQUIFAX_CREDIT_BUREAU',
    AmazonSpOnly: 'AMAZON_SP_ONLY',
    AmazonSpProxy: 'AMAZON_SP_PROXY',
    AmazonComplete: 'AMAZON_COMPLETE',
    Unknown: 'UNKNOWN'
} as const;
export type ScorecardResultScorecardTypeEnum = typeof ScorecardResultScorecardTypeEnum[keyof typeof ScorecardResultScorecardTypeEnum];


/**
 * Check if a given object implements the ScorecardResult interface.
 */
export function instanceOfScorecardResult(value: object): value is ScorecardResult {
    return true;
}

export function ScorecardResultFromJSON(json: any): ScorecardResult {
    return ScorecardResultFromJSONTyped(json, false);
}

export function ScorecardResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScorecardResult {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'dealId': json['dealId'] == null ? undefined : json['dealId'],
        'scorecardType': json['scorecardType'] == null ? undefined : json['scorecardType'],
        'score': json['score'] == null ? undefined : json['score'],
        'scorecardOutput': json['scorecardOutput'] == null ? undefined : json['scorecardOutput'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ScorecardResultToJSON(json: any): ScorecardResult {
    return ScorecardResultToJSONTyped(json, false);
}

export function ScorecardResultToJSONTyped(value?: ScorecardResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisationId': value['organisationId'],
        'dealId': value['dealId'],
        'scorecardType': value['scorecardType'],
        'score': value['score'],
        'scorecardOutput': value['scorecardOutput'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

