/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EligibilityBatchRequest,
  EligibilityBatchResponse,
  EligibilityResponse,
  OranisationSimpleResponse,
  OrganisationDTO,
  OrganisationDetailsResponse,
  OrganisationZoneId,
} from '../models/index';
import {
    EligibilityBatchRequestFromJSON,
    EligibilityBatchRequestToJSON,
    EligibilityBatchResponseFromJSON,
    EligibilityBatchResponseToJSON,
    EligibilityResponseFromJSON,
    EligibilityResponseToJSON,
    OranisationSimpleResponseFromJSON,
    OranisationSimpleResponseToJSON,
    OrganisationDTOFromJSON,
    OrganisationDTOToJSON,
    OrganisationDetailsResponseFromJSON,
    OrganisationDetailsResponseToJSON,
    OrganisationZoneIdFromJSON,
    OrganisationZoneIdToJSON,
} from '../models/index';

export interface GetOrganisationRequest {
    id: string;
    xXORGID: string;
}

export interface GetOrganisationByExternalIdRequest {
    externalId: string;
    xXORGID: string;
}

export interface GetOrganisationByNameRequest {
    name: string;
    xXORGID: string;
}

export interface GetOrganisationDetailsRequest {
    xXORGID: string;
}

export interface GetOrganisationInternalRequest {
    xXORGID: string;
}

export interface GetOrganisationZoneIdRequest {
    id: string;
    xXORGID: string;
}

export interface GetPotentialDuplicatesRequest {
    xXORGID: string;
    similarityThreshold?: number;
}

export interface IsEligibleRequest {
    organisationId: string;
    xXORGID: string;
}

export interface IsEligibleBatchRequest {
    xXORGID: string;
    eligibilityBatchRequest: EligibilityBatchRequest;
}

export interface SearchOrganisationsRequest {
    query: string;
    xXORGID: string;
}

/**
 * 
 */
export class OrganisationControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     * @deprecated
     */
    async getOrganisationRaw(requestParameters: GetOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganisation().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationDTOFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     * @deprecated
     */
    async getOrganisation(requestParameters: GetOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationDTO> {
        const response = await this.getOrganisationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationByExternalIdRaw(requestParameters: GetOrganisationByExternalIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationDTO>> {
        if (requestParameters['externalId'] == null) {
            throw new runtime.RequiredError(
                'externalId',
                'Required parameter "externalId" was null or undefined when calling getOrganisationByExternalId().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisationByExternalId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/externalId/{externalId}`;
        urlPath = urlPath.replace(`{${"externalId"}}`, encodeURIComponent(String(requestParameters['externalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationDTOFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationByExternalId(requestParameters: GetOrganisationByExternalIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationDTO> {
        const response = await this.getOrganisationByExternalIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationByNameRaw(requestParameters: GetOrganisationByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganisationDTO>>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getOrganisationByName().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisationByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/name/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationDTOFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationByName(requestParameters: GetOrganisationByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganisationDTO>> {
        const response = await this.getOrganisationByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     * @deprecated
     */
    async getOrganisationDetailsRaw(requestParameters: GetOrganisationDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationDetailsResponse>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisationDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/details`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationDetailsResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     * @deprecated
     */
    async getOrganisationDetails(requestParameters: GetOrganisationDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationDetailsResponse> {
        const response = await this.getOrganisationDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationInternalRaw(requestParameters: GetOrganisationInternalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationDTO>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisationInternal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/internal`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationDTOFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationInternal(requestParameters: GetOrganisationInternalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationDTO> {
        const response = await this.getOrganisationInternalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationZoneIdRaw(requestParameters: GetOrganisationZoneIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationZoneId>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganisationZoneId().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOrganisationZoneId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{id}/zone-id`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationZoneIdFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getOrganisationZoneId(requestParameters: GetOrganisationZoneIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationZoneId> {
        const response = await this.getOrganisationZoneIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getPotentialDuplicatesRaw(requestParameters: GetPotentialDuplicatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OranisationSimpleResponse>>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getPotentialDuplicates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['similarityThreshold'] != null) {
            queryParameters['similarityThreshold'] = requestParameters['similarityThreshold'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/potential-duplicates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OranisationSimpleResponseFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async getPotentialDuplicates(requestParameters: GetPotentialDuplicatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OranisationSimpleResponse>> {
        const response = await this.getPotentialDuplicatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async isEligibleRaw(requestParameters: IsEligibleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EligibilityResponse>> {
        if (requestParameters['organisationId'] == null) {
            throw new runtime.RequiredError(
                'organisationId',
                'Required parameter "organisationId" was null or undefined when calling isEligible().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling isEligible().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{organisationId}/eligibility`;
        urlPath = urlPath.replace(`{${"organisationId"}}`, encodeURIComponent(String(requestParameters['organisationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EligibilityResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async isEligible(requestParameters: IsEligibleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EligibilityResponse> {
        const response = await this.isEligibleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async isEligibleBatchRaw(requestParameters: IsEligibleBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EligibilityBatchResponse>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling isEligibleBatch().'
            );
        }

        if (requestParameters['eligibilityBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'eligibilityBatchRequest',
                'Required parameter "eligibilityBatchRequest" was null or undefined when calling isEligibleBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/eligibility/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EligibilityBatchRequestToJSON(requestParameters['eligibilityBatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EligibilityBatchResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async isEligibleBatch(requestParameters: IsEligibleBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EligibilityBatchResponse> {
        const response = await this.isEligibleBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async searchOrganisationsRaw(requestParameters: SearchOrganisationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganisationDTO>>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchOrganisations().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling searchOrganisations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationDTOFromJSON));
    }

    /**
     * This API requires **trusted** role.
     */
    async searchOrganisations(requestParameters: SearchOrganisationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganisationDTO>> {
        const response = await this.searchOrganisationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
