/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReEngageOrganisationRequest,
} from '../models/index';
import {
    ReEngageOrganisationRequestFromJSON,
    ReEngageOrganisationRequestToJSON,
} from '../models/index';

export interface GetInvitationsRequest {
    invitationId: string;
    xXORGID: string;
}

export interface ReEngageOrganisationOperationRequest {
    xXORGID: string;
    reEngageOrganisationRequest: ReEngageOrganisationRequest;
}

/**
 * 
 */
export class ReEngagementControllerApi extends runtime.BaseAPI {

    /**
     * This API is **public**.
     */
    async getInvitationsRaw(requestParameters: GetInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling getInvitations().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getInvitations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/re-engagement/{invitationId}/accept`;
        urlPath = urlPath.replace(`{${"invitationId"}}`, encodeURIComponent(String(requestParameters['invitationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API is **public**.
     */
    async getInvitations(requestParameters: GetInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getInvitationsRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async reEngageOrganisationRaw(requestParameters: ReEngageOrganisationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling reEngageOrganisation().'
            );
        }

        if (requestParameters['reEngageOrganisationRequest'] == null) {
            throw new runtime.RequiredError(
                'reEngageOrganisationRequest',
                'Required parameter "reEngageOrganisationRequest" was null or undefined when calling reEngageOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/re-engagement/invite`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReEngageOrganisationRequestToJSON(requestParameters['reEngageOrganisationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** role.
     */
    async reEngageOrganisation(requestParameters: ReEngageOrganisationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reEngageOrganisationRaw(requestParameters, initOverrides);
    }

}
