/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LeadDTO,
  RegistrationRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LeadDTOFromJSON,
    LeadDTOToJSON,
    RegistrationRequestFromJSON,
    RegistrationRequestToJSON,
} from '../models/index';

export interface RegisterUserWithSocialRequest {
    xXORGID: string;
    registrationRequest: RegistrationRequest;
}

/**
 * 
 */
export class RegistrationControllerApi extends runtime.BaseAPI {

    /**
     * This API is **public**.
     */
    async registerUserWithSocialRaw(requestParameters: RegisterUserWithSocialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeadDTO>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling registerUserWithSocial().'
            );
        }

        if (requestParameters['registrationRequest'] == null) {
            throw new runtime.RequiredError(
                'registrationRequest',
                'Required parameter "registrationRequest" was null or undefined when calling registerUserWithSocial().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user-registration/auth0`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationRequestToJSON(requestParameters['registrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeadDTOFromJSON(jsonValue));
    }

    /**
     * This API is **public**.
     */
    async registerUserWithSocial(requestParameters: RegisterUserWithSocialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeadDTO> {
        const response = await this.registerUserWithSocialRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
