/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionDTO
 */
export interface ConnectionDTO {
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    systemId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    connectionTemplateId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ConnectionDTO
     */
    data?: { [key: string]: object; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ConnectionDTO
     */
    errorData?: { [key: string]: object; };
    /**
     * 
     * @type {Date}
     * @memberof ConnectionDTO
     */
    enableDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    credentialsStatus?: ConnectionDTOCredentialsStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDTO
     */
    status?: ConnectionDTOStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ConnectionDTO
     */
    safePeriod?: number;
    /**
     * 
     * @type {Date}
     * @memberof ConnectionDTO
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConnectionDTO
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionDTO
     */
    deleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionDTO
     */
    disabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionDTO
     */
    hasError?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ConnectionDTOCredentialsStatusEnum {
    Exist = 'EXIST',
    NotExist = 'NOT_EXIST'
}/**
* @export
* @enum {string}
*/
export enum ConnectionDTOStatusEnum {
    Connecting = 'CONNECTING',
    Connected = 'CONNECTED',
    NotFinished = 'NOT_FINISHED',
    Error = 'ERROR',
    Duplicated = 'DUPLICATED',
    TemporaryDisabled = 'TEMPORARY_DISABLED',
    Deleted = 'DELETED'
}

export function ConnectionDTOFromJSON(json: any): ConnectionDTO {
    return ConnectionDTOFromJSONTyped(json, false);
}

export function ConnectionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'systemId': !exists(json, 'systemId') ? undefined : json['systemId'],
        'connectionTemplateId': !exists(json, 'connectionTemplateId') ? undefined : json['connectionTemplateId'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'organisationId': !exists(json, 'organisationId') ? undefined : json['organisationId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'errorData': !exists(json, 'errorData') ? undefined : json['errorData'],
        'enableDate': !exists(json, 'enableDate') ? undefined : (new Date(json['enableDate'])),
        'externalId': !exists(json, 'externalId') ? undefined : json['externalId'],
        'credentialsStatus': !exists(json, 'credentialsStatus') ? undefined : json['credentialsStatus'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'safePeriod': !exists(json, 'safePeriod') ? undefined : json['safePeriod'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'lastModifiedAt': !exists(json, 'lastModifiedAt') ? undefined : (new Date(json['lastModifiedAt'])),
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'hasError': !exists(json, 'hasError') ? undefined : json['hasError'],
    };
}

export function ConnectionDTOToJSON(value?: ConnectionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'systemId': value.systemId,
        'connectionTemplateId': value.connectionTemplateId,
        'type': value.type,
        'organisationId': value.organisationId,
        'name': value.name,
        'data': value.data,
        'errorData': value.errorData,
        'enableDate': value.enableDate === undefined ? undefined : (value.enableDate.toISOString()),
        'externalId': value.externalId,
        'credentialsStatus': value.credentialsStatus,
        'status': value.status,
        'safePeriod': value.safePeriod,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
        'lastModifiedAt': value.lastModifiedAt === undefined ? undefined : (value.lastModifiedAt.toISOString()),
        'deleted': value.deleted,
        'disabled': value.disabled,
        'hasError': value.hasError,
    };
}

