/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DestroyCallback
 */
export interface DestroyCallback {
    /**
     * 
     * @type {string}
     * @memberof DestroyCallback
     */
    connectionId?: string;
    /**
     * 
     * @type {string}
     * @memberof DestroyCallback
     */
    customerId?: string;
}

export function DestroyCallbackFromJSON(json: any): DestroyCallback {
    return DestroyCallbackFromJSONTyped(json, false);
}

export function DestroyCallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestroyCallback {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionId': !exists(json, 'connection_id') ? undefined : json['connection_id'],
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
    };
}

export function DestroyCallbackToJSON(value?: DestroyCallback | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connection_id': value.connectionId,
        'customer_id': value.customerId,
    };
}

