/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LastAttempt
 */
export interface LastAttempt {
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    failAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    successAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    failErrorClass?: string;
    /**
     * 
     * @type {string}
     * @memberof LastAttempt
     */
    failMessage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LastAttempt
     */
    finished?: boolean;
}

export function LastAttemptFromJSON(json: any): LastAttempt {
    return LastAttemptFromJSONTyped(json, false);
}

export function LastAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastAttempt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'failAt': !exists(json, 'failAt') ? undefined : json['failAt'],
        'successAt': !exists(json, 'successAt') ? undefined : json['successAt'],
        'failErrorClass': !exists(json, 'failErrorClass') ? undefined : json['failErrorClass'],
        'failMessage': !exists(json, 'failMessage') ? undefined : json['failMessage'],
        'finished': !exists(json, 'finished') ? undefined : json['finished'],
    };
}

export function LastAttemptToJSON(value?: LastAttempt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'failAt': value.failAt,
        'successAt': value.successAt,
        'failErrorClass': value.failErrorClass,
        'failMessage': value.failMessage,
        'finished': value.finished,
    };
}

