/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AuditLogDetails,
    AuditLogDetailsFromJSON,
    AuditLogDetailsFromJSONTyped,
    AuditLogDetailsToJSON,
} from './AuditLogDetails';

/**
 * 
 * @export
 * @interface PageModelAuditLogDetails
 */
export interface PageModelAuditLogDetails {
    /**
     * 
     * @type {Array<AuditLogDetails>}
     * @memberof PageModelAuditLogDetails
     */
    content?: Array<AuditLogDetails>;
    /**
     * 
     * @type {number}
     * @memberof PageModelAuditLogDetails
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModelAuditLogDetails
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModelAuditLogDetails
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModelAuditLogDetails
     */
    totalPages?: number;
}

export function PageModelAuditLogDetailsFromJSON(json: any): PageModelAuditLogDetails {
    return PageModelAuditLogDetailsFromJSONTyped(json, false);
}

export function PageModelAuditLogDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageModelAuditLogDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(AuditLogDetailsFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
    };
}

export function PageModelAuditLogDetailsToJSON(value?: PageModelAuditLogDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(AuditLogDetailsToJSON)),
        'page': value.page,
        'size': value.size,
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
    };
}

