/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidUserEventMetadata
 */
export interface PlaidUserEventMetadata {
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    errorType?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    exitStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    institutionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    institutionName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    institutionSearchQuery?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    isUpdateMode?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    matchReason?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    routingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    mfaType?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    viewName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    linkSessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidUserEventMetadata
     */
    selection?: string;
}

export function PlaidUserEventMetadataFromJSON(json: any): PlaidUserEventMetadata {
    return PlaidUserEventMetadataFromJSONTyped(json, false);
}

export function PlaidUserEventMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidUserEventMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorType': !exists(json, 'errorType') ? undefined : json['errorType'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'exitStatus': !exists(json, 'exitStatus') ? undefined : json['exitStatus'],
        'institutionId': !exists(json, 'institutionId') ? undefined : json['institutionId'],
        'institutionName': !exists(json, 'institutionName') ? undefined : json['institutionName'],
        'institutionSearchQuery': !exists(json, 'institutionSearchQuery') ? undefined : json['institutionSearchQuery'],
        'isUpdateMode': !exists(json, 'isUpdateMode') ? undefined : json['isUpdateMode'],
        'matchReason': !exists(json, 'matchReason') ? undefined : json['matchReason'],
        'routingNumber': !exists(json, 'routingNumber') ? undefined : json['routingNumber'],
        'mfaType': !exists(json, 'mfaType') ? undefined : json['mfaType'],
        'viewName': !exists(json, 'viewName') ? undefined : json['viewName'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'linkSessionId': !exists(json, 'linkSessionId') ? undefined : json['linkSessionId'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'selection': !exists(json, 'selection') ? undefined : json['selection'],
    };
}

export function PlaidUserEventMetadataToJSON(value?: PlaidUserEventMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorType': value.errorType,
        'errorCode': value.errorCode,
        'errorMessage': value.errorMessage,
        'exitStatus': value.exitStatus,
        'institutionId': value.institutionId,
        'institutionName': value.institutionName,
        'institutionSearchQuery': value.institutionSearchQuery,
        'isUpdateMode': value.isUpdateMode,
        'matchReason': value.matchReason,
        'routingNumber': value.routingNumber,
        'mfaType': value.mfaType,
        'viewName': value.viewName,
        'requestId': value.requestId,
        'linkSessionId': value.linkSessionId,
        'timestamp': value.timestamp,
        'selection': value.selection,
    };
}

