/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidInstitution
 */
export interface PlaidInstitution {
    /**
     * 
     * @type {string}
     * @memberof PlaidInstitution
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidInstitution
     */
    institutionId?: string;
}

export function PlaidInstitutionFromJSON(json: any): PlaidInstitution {
    return PlaidInstitutionFromJSONTyped(json, false);
}

export function PlaidInstitutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidInstitution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'institutionId': !exists(json, 'institution_id') ? undefined : json['institution_id'],
    };
}

export function PlaidInstitutionToJSON(value?: PlaidInstitution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'institution_id': value.institutionId,
    };
}

