/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicantUserAddressOverview
 */
export interface ApplicantUserAddressOverview {
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    buildingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    apartmentNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    stateRegion?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantUserAddressOverview
     */
    country?: string;
}

/**
 * Check if a given object implements the ApplicantUserAddressOverview interface.
 */
export function instanceOfApplicantUserAddressOverview(value: object): value is ApplicantUserAddressOverview {
    return true;
}

export function ApplicantUserAddressOverviewFromJSON(json: any): ApplicantUserAddressOverview {
    return ApplicantUserAddressOverviewFromJSONTyped(json, false);
}

export function ApplicantUserAddressOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicantUserAddressOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'buildingNumber': json['buildingNumber'] == null ? undefined : json['buildingNumber'],
        'apartmentNumber': json['apartmentNumber'] == null ? undefined : json['apartmentNumber'],
        'city': json['city'] == null ? undefined : json['city'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'stateRegion': json['stateRegion'] == null ? undefined : json['stateRegion'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function ApplicantUserAddressOverviewToJSON(json: any): ApplicantUserAddressOverview {
    return ApplicantUserAddressOverviewToJSONTyped(json, false);
}

export function ApplicantUserAddressOverviewToJSONTyped(value?: ApplicantUserAddressOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'buildingNumber': value['buildingNumber'],
        'apartmentNumber': value['apartmentNumber'],
        'city': value['city'],
        'zip': value['zip'],
        'stateRegion': value['stateRegion'],
        'country': value['country'],
    };
}

