/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface CompanyDetails
 */
export interface CompanyDetails {
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    legalName?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    companyRegistrationId?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    legalStructure?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    mainRevenueSource?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    mainStoreUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails
     */
    ecommercePlatform?: CompanyDetailsEcommercePlatformEnum;
    /**
     * 
     * @type {Address}
     * @memberof CompanyDetails
     */
    address?: Address;
}


/**
 * @export
 */
export const CompanyDetailsEcommercePlatformEnum = {
    Amazon: 'Amazon',
    Walmart: 'Walmart',
    Shopify: 'Shopify',
    WooCommerce: 'WooCommerce',
    Other: 'Other',
    None: 'None'
} as const;
export type CompanyDetailsEcommercePlatformEnum = typeof CompanyDetailsEcommercePlatformEnum[keyof typeof CompanyDetailsEcommercePlatformEnum];


/**
 * Check if a given object implements the CompanyDetails interface.
 */
export function instanceOfCompanyDetails(value: object): value is CompanyDetails {
    return true;
}

export function CompanyDetailsFromJSON(json: any): CompanyDetails {
    return CompanyDetailsFromJSONTyped(json, false);
}

export function CompanyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'legalName': json['legalName'] == null ? undefined : json['legalName'],
        'companyRegistrationId': json['companyRegistrationId'] == null ? undefined : json['companyRegistrationId'],
        'legalStructure': json['legalStructure'] == null ? undefined : json['legalStructure'],
        'mainRevenueSource': json['mainRevenueSource'] == null ? undefined : json['mainRevenueSource'],
        'mainStoreUrl': json['mainStoreUrl'] == null ? undefined : json['mainStoreUrl'],
        'ecommercePlatform': json['ecommercePlatform'] == null ? undefined : json['ecommercePlatform'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
    };
}

export function CompanyDetailsToJSON(json: any): CompanyDetails {
    return CompanyDetailsToJSONTyped(json, false);
}

export function CompanyDetailsToJSONTyped(value?: CompanyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'legalName': value['legalName'],
        'companyRegistrationId': value['companyRegistrationId'],
        'legalStructure': value['legalStructure'],
        'mainRevenueSource': value['mainRevenueSource'],
        'mainStoreUrl': value['mainStoreUrl'],
        'ecommercePlatform': value['ecommercePlatform'],
        'address': AddressToJSON(value['address']),
    };
}

