/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryStock
 */
export interface InventoryStock {
    /**
     * 
     * @type {boolean}
     * @memberof InventoryStock
     */
    isPresent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InventoryStock
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof InventoryStock
     */
    totalValue?: number;
}

/**
 * Check if a given object implements the InventoryStock interface.
 */
export function instanceOfInventoryStock(value: object): value is InventoryStock {
    return true;
}

export function InventoryStockFromJSON(json: any): InventoryStock {
    return InventoryStockFromJSONTyped(json, false);
}

export function InventoryStockFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryStock {
    if (json == null) {
        return json;
    }
    return {
        
        'isPresent': json['isPresent'] == null ? undefined : json['isPresent'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'totalValue': json['totalValue'] == null ? undefined : json['totalValue'],
    };
}

export function InventoryStockToJSON(json: any): InventoryStock {
    return InventoryStockToJSONTyped(json, false);
}

export function InventoryStockToJSONTyped(value?: InventoryStock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPresent': value['isPresent'],
        'currency': value['currency'],
        'totalValue': value['totalValue'],
    };
}

