/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributionResponse } from './AttributionResponse';
import {
    AttributionResponseFromJSON,
    AttributionResponseFromJSONTyped,
    AttributionResponseToJSON,
    AttributionResponseToJSONTyped,
} from './AttributionResponse';

/**
 * 
 * @export
 * @interface OrganisationAttributionsResponse
 */
export interface OrganisationAttributionsResponse {
    /**
     * 
     * @type {AttributionResponse}
     * @memberof OrganisationAttributionsResponse
     */
    attribution?: AttributionResponse;
}

/**
 * Check if a given object implements the OrganisationAttributionsResponse interface.
 */
export function instanceOfOrganisationAttributionsResponse(value: object): value is OrganisationAttributionsResponse {
    return true;
}

export function OrganisationAttributionsResponseFromJSON(json: any): OrganisationAttributionsResponse {
    return OrganisationAttributionsResponseFromJSONTyped(json, false);
}

export function OrganisationAttributionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationAttributionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'attribution': json['attribution'] == null ? undefined : AttributionResponseFromJSON(json['attribution']),
    };
}

export function OrganisationAttributionsResponseToJSON(json: any): OrganisationAttributionsResponse {
    return OrganisationAttributionsResponseToJSONTyped(json, false);
}

export function OrganisationAttributionsResponseToJSONTyped(value?: OrganisationAttributionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribution': AttributionResponseToJSON(value['attribution']),
    };
}

