/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnersEligibilityCheckResponse
 */
export interface PartnersEligibilityCheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PartnersEligibilityCheckResponse
     */
    isEligible?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PartnersEligibilityCheckResponse
     */
    eligibleAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PartnersEligibilityCheckResponse
     */
    eligibleCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnersEligibilityCheckResponse
     */
    notEligibleReason?: PartnersEligibilityCheckResponseNotEligibleReasonEnum;
}


/**
 * @export
 */
export const PartnersEligibilityCheckResponseNotEligibleReasonEnum = {
    SoleTrader: 'SOLE_TRADER',
    UnsupportedUsState: 'UNSUPPORTED_US_STATE',
    UnsupportedCanadaProvince: 'UNSUPPORTED_CANADA_PROVINCE',
    UnsupportedBusinessType: 'UNSUPPORTED_BUSINESS_TYPE',
    UnsupportedCountry: 'UNSUPPORTED_COUNTRY',
    LowRevenue: 'LOW_REVENUE'
} as const;
export type PartnersEligibilityCheckResponseNotEligibleReasonEnum = typeof PartnersEligibilityCheckResponseNotEligibleReasonEnum[keyof typeof PartnersEligibilityCheckResponseNotEligibleReasonEnum];


/**
 * Check if a given object implements the PartnersEligibilityCheckResponse interface.
 */
export function instanceOfPartnersEligibilityCheckResponse(value: object): value is PartnersEligibilityCheckResponse {
    return true;
}

export function PartnersEligibilityCheckResponseFromJSON(json: any): PartnersEligibilityCheckResponse {
    return PartnersEligibilityCheckResponseFromJSONTyped(json, false);
}

export function PartnersEligibilityCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnersEligibilityCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isEligible': json['isEligible'] == null ? undefined : json['isEligible'],
        'eligibleAmount': json['eligibleAmount'] == null ? undefined : json['eligibleAmount'],
        'eligibleCurrency': json['eligibleCurrency'] == null ? undefined : json['eligibleCurrency'],
        'notEligibleReason': json['notEligibleReason'] == null ? undefined : json['notEligibleReason'],
    };
}

export function PartnersEligibilityCheckResponseToJSON(json: any): PartnersEligibilityCheckResponse {
    return PartnersEligibilityCheckResponseToJSONTyped(json, false);
}

export function PartnersEligibilityCheckResponseToJSONTyped(value?: PartnersEligibilityCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isEligible': value['isEligible'],
        'eligibleAmount': value['eligibleAmount'],
        'eligibleCurrency': value['eligibleCurrency'],
        'notEligibleReason': value['notEligibleReason'],
    };
}

