/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketingData } from './MarketingData';
import {
    MarketingDataFromJSON,
    MarketingDataFromJSONTyped,
    MarketingDataToJSON,
    MarketingDataToJSONTyped,
} from './MarketingData';

/**
 * 
 * @export
 * @interface RegistrationRequest
 */
export interface RegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    externalUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    email: string;
    /**
     * 
     * @type {MarketingData}
     * @memberof RegistrationRequest
     */
    marketingData?: MarketingData;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    prospectId?: string;
}

/**
 * Check if a given object implements the RegistrationRequest interface.
 */
export function instanceOfRegistrationRequest(value: object): value is RegistrationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegistrationRequestFromJSON(json: any): RegistrationRequest {
    return RegistrationRequestFromJSONTyped(json, false);
}

export function RegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'externalUserId': json['externalUserId'] == null ? undefined : json['externalUserId'],
        'password': json['password'] == null ? undefined : json['password'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'],
        'marketingData': json['marketingData'] == null ? undefined : MarketingDataFromJSON(json['marketingData']),
        'prospectId': json['prospectId'] == null ? undefined : json['prospectId'],
    };
}

export function RegistrationRequestToJSON(json: any): RegistrationRequest {
    return RegistrationRequestToJSONTyped(json, false);
}

export function RegistrationRequestToJSONTyped(value?: RegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalUserId': value['externalUserId'],
        'password': value['password'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'marketingData': MarketingDataToJSON(value['marketingData']),
        'prospectId': value['prospectId'],
    };
}

