/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MissingDocumentResponse } from './MissingDocumentResponse';
import {
    MissingDocumentResponseFromJSON,
    MissingDocumentResponseFromJSONTyped,
    MissingDocumentResponseToJSON,
    MissingDocumentResponseToJSONTyped,
} from './MissingDocumentResponse';
import type { UploadedDocumentResponse } from './UploadedDocumentResponse';
import {
    UploadedDocumentResponseFromJSON,
    UploadedDocumentResponseFromJSONTyped,
    UploadedDocumentResponseToJSON,
    UploadedDocumentResponseToJSONTyped,
} from './UploadedDocumentResponse';

/**
 * 
 * @export
 * @interface RequiredDocumentsResponse
 */
export interface RequiredDocumentsResponse {
    /**
     * 
     * @type {Array<MissingDocumentResponse>}
     * @memberof RequiredDocumentsResponse
     */
    requiredDocuments?: Array<MissingDocumentResponse>;
    /**
     * 
     * @type {Array<UploadedDocumentResponse>}
     * @memberof RequiredDocumentsResponse
     */
    uploadedDocuments?: Array<UploadedDocumentResponse>;
}

/**
 * Check if a given object implements the RequiredDocumentsResponse interface.
 */
export function instanceOfRequiredDocumentsResponse(value: object): value is RequiredDocumentsResponse {
    return true;
}

export function RequiredDocumentsResponseFromJSON(json: any): RequiredDocumentsResponse {
    return RequiredDocumentsResponseFromJSONTyped(json, false);
}

export function RequiredDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredDocumentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requiredDocuments': json['requiredDocuments'] == null ? undefined : ((json['requiredDocuments'] as Array<any>).map(MissingDocumentResponseFromJSON)),
        'uploadedDocuments': json['uploadedDocuments'] == null ? undefined : ((json['uploadedDocuments'] as Array<any>).map(UploadedDocumentResponseFromJSON)),
    };
}

export function RequiredDocumentsResponseToJSON(json: any): RequiredDocumentsResponse {
    return RequiredDocumentsResponseToJSONTyped(json, false);
}

export function RequiredDocumentsResponseToJSONTyped(value?: RequiredDocumentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requiredDocuments': value['requiredDocuments'] == null ? undefined : ((value['requiredDocuments'] as Array<any>).map(MissingDocumentResponseToJSON)),
        'uploadedDocuments': value['uploadedDocuments'] == null ? undefined : ((value['uploadedDocuments'] as Array<any>).map(UploadedDocumentResponseToJSON)),
    };
}

