/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileDTO
 */
export interface UserProfileDTO {
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    slackId?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDTO
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDTO
     */
    lastUpdated?: Date;
}

/**
 * Check if a given object implements the UserProfileDTO interface.
 */
export function instanceOfUserProfileDTO(value: object): value is UserProfileDTO {
    return true;
}

export function UserProfileDTOFromJSON(json: any): UserProfileDTO {
    return UserProfileDTOFromJSONTyped(json, false);
}

export function UserProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'slackId': json['slackId'] == null ? undefined : json['slackId'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
    };
}

export function UserProfileDTOToJSON(json: any): UserProfileDTO {
    return UserProfileDTOToJSONTyped(json, false);
}

export function UserProfileDTOToJSONTyped(value?: UserProfileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
        'name': value['name'],
        'email': value['email'],
        'slackId': value['slackId'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'lastUpdated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
    };
}

