/* tslint:disable */
/* eslint-disable */
/**
 * api-organisation-users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @project.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOrganisationReassignRequest
 */
export interface UserOrganisationReassignRequest {
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationReassignRequest
     */
    newOrganisationId: string;
}

/**
 * Check if a given object implements the UserOrganisationReassignRequest interface.
 */
export function instanceOfUserOrganisationReassignRequest(value: object): value is UserOrganisationReassignRequest {
    if (!('newOrganisationId' in value) || value['newOrganisationId'] === undefined) return false;
    return true;
}

export function UserOrganisationReassignRequestFromJSON(json: any): UserOrganisationReassignRequest {
    return UserOrganisationReassignRequestFromJSONTyped(json, false);
}

export function UserOrganisationReassignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOrganisationReassignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newOrganisationId': json['newOrganisationId'],
    };
}

export function UserOrganisationReassignRequestToJSON(json: any): UserOrganisationReassignRequest {
    return UserOrganisationReassignRequestToJSONTyped(json, false);
}

export function UserOrganisationReassignRequestToJSONTyped(value?: UserOrganisationReassignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newOrganisationId': value['newOrganisationId'],
    };
}

