/* tslint:disable */
/* eslint-disable */
/**
 * api-partners
 * Change log: <br>1.0.0 initial release
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PreOfferEstimationRequest,
  PreOfferEstimationResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PreOfferEstimationRequestFromJSON,
    PreOfferEstimationRequestToJSON,
    PreOfferEstimationResponseFromJSON,
    PreOfferEstimationResponseToJSON,
} from '../models/index';

export interface GeneratePreOfferEstimationRequest {
    preOfferEstimationRequest: PreOfferEstimationRequest;
}

/**
 * 
 */
export class EstimationsApi extends runtime.BaseAPI {

    /**
     * Generates pre-offer estimations based on partner applicant performance data.  **Revenue Data:** - Submit revenue figures grouped by source (e.g., AMAZON, SHOPIFY) - Each source contains an array of revenue figures  **Currency Determination:** - Currency is automatically determined from country code (e.g., USA→ USD) - Uses ISO 3166-1 alpha-2 to ISO 4217 mapping - Revenue currency from figures is used for calculations, but response currency comes from country  **Partner Integration Guidelines:** - Use ISO 8601 date format (yyyy-MM-dd) - Use ISO 4217 currency codes (e.g., USD, EUR, GBP) - Use ISO 3166-1 alpha-3 country codes (e.g., USA, CAN, GBR, POL) - Use ISO 3166-2 state codes (e.g., CA, NY, TX, ON) 
     * Generate pre-offer estimations
     */
    async generatePreOfferEstimationRaw(requestParameters: GeneratePreOfferEstimationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreOfferEstimationResponse>> {
        if (requestParameters['preOfferEstimationRequest'] == null) {
            throw new runtime.RequiredError(
                'preOfferEstimationRequest',
                'Required parameter "preOfferEstimationRequest" was null or undefined when calling generatePreOfferEstimation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/estimations/pre-offers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PreOfferEstimationRequestToJSON(requestParameters['preOfferEstimationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreOfferEstimationResponseFromJSON(jsonValue));
    }

    /**
     * Generates pre-offer estimations based on partner applicant performance data.  **Revenue Data:** - Submit revenue figures grouped by source (e.g., AMAZON, SHOPIFY) - Each source contains an array of revenue figures  **Currency Determination:** - Currency is automatically determined from country code (e.g., USA→ USD) - Uses ISO 3166-1 alpha-2 to ISO 4217 mapping - Revenue currency from figures is used for calculations, but response currency comes from country  **Partner Integration Guidelines:** - Use ISO 8601 date format (yyyy-MM-dd) - Use ISO 4217 currency codes (e.g., USD, EUR, GBP) - Use ISO 3166-1 alpha-3 country codes (e.g., USA, CAN, GBR, POL) - Use ISO 3166-2 state codes (e.g., CA, NY, TX, ON) 
     * Generate pre-offer estimations
     */
    async generatePreOfferEstimation(requestParameters: GeneratePreOfferEstimationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreOfferEstimationResponse> {
        const response = await this.generatePreOfferEstimationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
