/* tslint:disable */
/* eslint-disable */
/**
 * api-partners
 * Change log: <br>1.0.0 initial release
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetAllEnabledFlagsRequest {
    xXPARTNERID: string;
}

export interface GetSingleFlagValueRequest {
    flagName: string;
    xXPARTNERID: string;
}

/**
 * 
 */
export class FlagValuesControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllEnabledFlagsRaw(requestParameters: GetAllEnabledFlagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: boolean; }>> {
        if (requestParameters['xXPARTNERID'] == null) {
            throw new runtime.RequiredError(
                'xXPARTNERID',
                'Required parameter "xXPARTNERID" was null or undefined when calling getAllEnabledFlags().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXPARTNERID'] != null) {
            headerParameters['XX-PARTNER-ID'] = String(requestParameters['xXPARTNERID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/featureflag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getAllEnabledFlags(requestParameters: GetAllEnabledFlagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: boolean; }> {
        const response = await this.getAllEnabledFlagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSingleFlagValueRaw(requestParameters: GetSingleFlagValueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['flagName'] == null) {
            throw new runtime.RequiredError(
                'flagName',
                'Required parameter "flagName" was null or undefined when calling getSingleFlagValue().'
            );
        }

        if (requestParameters['xXPARTNERID'] == null) {
            throw new runtime.RequiredError(
                'xXPARTNERID',
                'Required parameter "xXPARTNERID" was null or undefined when calling getSingleFlagValue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXPARTNERID'] != null) {
            headerParameters['XX-PARTNER-ID'] = String(requestParameters['xXPARTNERID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/featureflag/{flagName}`;
        urlPath = urlPath.replace(`{${"flagName"}}`, encodeURIComponent(String(requestParameters['flagName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getSingleFlagValue(requestParameters: GetSingleFlagValueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getSingleFlagValueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
