/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdjustmentRequest
 */
export interface AdjustmentRequest {
    /**
     * 
     * @type {string}
     * @memberof AdjustmentRequest
     */
    agreementId: string;
    /**
     * 
     * @type {string}
     * @memberof AdjustmentRequest
     */
    organisationId: string;
    /**
     * 
     * @type {number}
     * @memberof AdjustmentRequest
     */
    principal: number;
    /**
     * 
     * @type {number}
     * @memberof AdjustmentRequest
     */
    interest: number;
    /**
     * 
     * @type {number}
     * @memberof AdjustmentRequest
     */
    fee: number;
    /**
     * 
     * @type {string}
     * @memberof AdjustmentRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof AdjustmentRequest
     */
    description: string;
}

/**
 * Check if a given object implements the AdjustmentRequest interface.
 */
export function instanceOfAdjustmentRequest(value: object): value is AdjustmentRequest {
    if (!('agreementId' in value) || value['agreementId'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('principal' in value) || value['principal'] === undefined) return false;
    if (!('interest' in value) || value['interest'] === undefined) return false;
    if (!('fee' in value) || value['fee'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function AdjustmentRequestFromJSON(json: any): AdjustmentRequest {
    return AdjustmentRequestFromJSONTyped(json, false);
}

export function AdjustmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementId': json['agreementId'],
        'organisationId': json['organisationId'],
        'principal': json['principal'],
        'interest': json['interest'],
        'fee': json['fee'],
        'currency': json['currency'],
        'description': json['description'],
    };
}

export function AdjustmentRequestToJSON(json: any): AdjustmentRequest {
    return AdjustmentRequestToJSONTyped(json, false);
}

export function AdjustmentRequestToJSONTyped(value?: AdjustmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreementId': value['agreementId'],
        'organisationId': value['organisationId'],
        'principal': value['principal'],
        'interest': value['interest'],
        'fee': value['fee'],
        'currency': value['currency'],
        'description': value['description'],
    };
}

