/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgreementValidCurrencyResponse
 */
export interface AgreementValidCurrencyResponse {
    /**
     * 
     * @type {string}
     * @memberof AgreementValidCurrencyResponse
     */
    validCurrency?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgreementValidCurrencyResponse
     */
    availableCurrencies?: Array<string>;
}

/**
 * Check if a given object implements the AgreementValidCurrencyResponse interface.
 */
export function instanceOfAgreementValidCurrencyResponse(value: object): value is AgreementValidCurrencyResponse {
    return true;
}

export function AgreementValidCurrencyResponseFromJSON(json: any): AgreementValidCurrencyResponse {
    return AgreementValidCurrencyResponseFromJSONTyped(json, false);
}

export function AgreementValidCurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgreementValidCurrencyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validCurrency': json['validCurrency'] == null ? undefined : json['validCurrency'],
        'availableCurrencies': json['availableCurrencies'] == null ? undefined : json['availableCurrencies'],
    };
}

export function AgreementValidCurrencyResponseToJSON(json: any): AgreementValidCurrencyResponse {
    return AgreementValidCurrencyResponseToJSONTyped(json, false);
}

export function AgreementValidCurrencyResponseToJSONTyped(value?: AgreementValidCurrencyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validCurrency': value['validCurrency'],
        'availableCurrencies': value['availableCurrencies'],
    };
}

