/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailableTypeForAgreement
 */
export interface AvailableTypeForAgreement {
    /**
     * 
     * @type {string}
     * @memberof AvailableTypeForAgreement
     */
    agreementId?: string;
    /**
     * 
     * @type {string}
     * @memberof AvailableTypeForAgreement
     */
    availableRepaymentType?: AvailableTypeForAgreementAvailableRepaymentTypeEnum;
}


/**
 * @export
 */
export const AvailableTypeForAgreementAvailableRepaymentTypeEnum = {
    AnyAmount: 'ANY_AMOUNT',
    FullLeftToRepayOnly: 'FULL_LEFT_TO_REPAY_ONLY'
} as const;
export type AvailableTypeForAgreementAvailableRepaymentTypeEnum = typeof AvailableTypeForAgreementAvailableRepaymentTypeEnum[keyof typeof AvailableTypeForAgreementAvailableRepaymentTypeEnum];


/**
 * Check if a given object implements the AvailableTypeForAgreement interface.
 */
export function instanceOfAvailableTypeForAgreement(value: object): value is AvailableTypeForAgreement {
    return true;
}

export function AvailableTypeForAgreementFromJSON(json: any): AvailableTypeForAgreement {
    return AvailableTypeForAgreementFromJSONTyped(json, false);
}

export function AvailableTypeForAgreementFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableTypeForAgreement {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementId': json['agreementId'] == null ? undefined : json['agreementId'],
        'availableRepaymentType': json['availableRepaymentType'] == null ? undefined : json['availableRepaymentType'],
    };
}

export function AvailableTypeForAgreementToJSON(json: any): AvailableTypeForAgreement {
    return AvailableTypeForAgreementToJSONTyped(json, false);
}

export function AvailableTypeForAgreementToJSONTyped(value?: AvailableTypeForAgreement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreementId': value['agreementId'],
        'availableRepaymentType': value['availableRepaymentType'],
    };
}

