/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProblemDetail } from './ProblemDetail';
import {
    ProblemDetailFromJSON,
    ProblemDetailFromJSONTyped,
    ProblemDetailToJSON,
    ProblemDetailToJSONTyped,
} from './ProblemDetail';
import type { HttpHeaders } from './HttpHeaders';
import {
    HttpHeadersFromJSON,
    HttpHeadersFromJSONTyped,
    HttpHeadersToJSON,
    HttpHeadersToJSONTyped,
} from './HttpHeaders';
import type { CodeMessage } from './CodeMessage';
import {
    CodeMessageFromJSON,
    CodeMessageFromJSONTyped,
    CodeMessageToJSON,
    CodeMessageToJSONTyped,
} from './CodeMessage';
import type { BusinessRestExceptionRootCause } from './BusinessRestExceptionRootCause';
import {
    BusinessRestExceptionRootCauseFromJSON,
    BusinessRestExceptionRootCauseFromJSONTyped,
    BusinessRestExceptionRootCauseToJSON,
    BusinessRestExceptionRootCauseToJSONTyped,
} from './BusinessRestExceptionRootCause';
import type { BusinessRestExceptionHeaders } from './BusinessRestExceptionHeaders';
import {
    BusinessRestExceptionHeadersFromJSON,
    BusinessRestExceptionHeadersFromJSONTyped,
    BusinessRestExceptionHeadersToJSON,
    BusinessRestExceptionHeadersToJSONTyped,
} from './BusinessRestExceptionHeaders';
import type { BusinessRestExceptionStatusCode } from './BusinessRestExceptionStatusCode';
import {
    BusinessRestExceptionStatusCodeFromJSON,
    BusinessRestExceptionStatusCodeFromJSONTyped,
    BusinessRestExceptionStatusCodeToJSON,
    BusinessRestExceptionStatusCodeToJSONTyped,
} from './BusinessRestExceptionStatusCode';
import type { BusinessRestExceptionCause } from './BusinessRestExceptionCause';
import {
    BusinessRestExceptionCauseFromJSON,
    BusinessRestExceptionCauseFromJSONTyped,
    BusinessRestExceptionCauseToJSON,
    BusinessRestExceptionCauseToJSONTyped,
} from './BusinessRestExceptionCause';
import type { BusinessRestExceptionCauseStackTraceInner } from './BusinessRestExceptionCauseStackTraceInner';
import {
    BusinessRestExceptionCauseStackTraceInnerFromJSON,
    BusinessRestExceptionCauseStackTraceInnerFromJSONTyped,
    BusinessRestExceptionCauseStackTraceInnerToJSON,
    BusinessRestExceptionCauseStackTraceInnerToJSONTyped,
} from './BusinessRestExceptionCauseStackTraceInner';

/**
 * 
 * @export
 * @interface BusinessRestException
 */
export interface BusinessRestException {
    /**
     * 
     * @type {BusinessRestExceptionCause}
     * @memberof BusinessRestException
     */
    cause?: BusinessRestExceptionCause;
    /**
     * 
     * @type {Array<BusinessRestExceptionCauseStackTraceInner>}
     * @memberof BusinessRestException
     */
    stackTrace?: Array<BusinessRestExceptionCauseStackTraceInner>;
    /**
     * 
     * @type {BusinessRestExceptionHeaders}
     * @memberof BusinessRestException
     */
    headers?: BusinessRestExceptionHeaders;
    /**
     * 
     * @type {ProblemDetail}
     * @memberof BusinessRestException
     */
    body?: ProblemDetail;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    message?: string;
    /**
     * 
     * @type {Array<CodeMessage>}
     * @memberof BusinessRestException
     */
    details?: Array<CodeMessage>;
    /**
     * 
     * @type {HttpHeaders}
     * @memberof BusinessRestException
     * @deprecated
     */
    responseHeaders?: HttpHeaders;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    instance?: string;
    /**
     * 
     * @type {BusinessRestExceptionStatusCode}
     * @memberof BusinessRestException
     */
    statusCode?: BusinessRestExceptionStatusCode;
    /**
     * 
     * @type {Array<any>}
     * @memberof BusinessRestException
     */
    detailMessageArguments?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    detailMessageCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    typeMessageCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    titleMessageCode?: string;
    /**
     * 
     * @type {BusinessRestExceptionRootCause}
     * @memberof BusinessRestException
     */
    rootCause?: BusinessRestExceptionRootCause;
    /**
     * 
     * @type {BusinessRestExceptionCause}
     * @memberof BusinessRestException
     */
    mostSpecificCause?: BusinessRestExceptionCause;
    /**
     * 
     * @type {Array<BusinessRestExceptionCause>}
     * @memberof BusinessRestException
     */
    suppressed?: Array<BusinessRestExceptionCause>;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestException
     */
    localizedMessage?: string;
}

/**
 * Check if a given object implements the BusinessRestException interface.
 */
export function instanceOfBusinessRestException(value: object): value is BusinessRestException {
    return true;
}

export function BusinessRestExceptionFromJSON(json: any): BusinessRestException {
    return BusinessRestExceptionFromJSONTyped(json, false);
}

export function BusinessRestExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRestException {
    if (json == null) {
        return json;
    }
    return {
        
        'cause': json['cause'] == null ? undefined : BusinessRestExceptionCauseFromJSON(json['cause']),
        'stackTrace': json['stackTrace'] == null ? undefined : ((json['stackTrace'] as Array<any>).map(BusinessRestExceptionCauseStackTraceInnerFromJSON)),
        'headers': json['headers'] == null ? undefined : BusinessRestExceptionHeadersFromJSON(json['headers']),
        'body': json['body'] == null ? undefined : ProblemDetailFromJSON(json['body']),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(CodeMessageFromJSON)),
        'responseHeaders': json['responseHeaders'] == null ? undefined : HttpHeadersFromJSON(json['responseHeaders']),
        'detail': json['detail'] == null ? undefined : json['detail'],
        'title': json['title'] == null ? undefined : json['title'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'statusCode': json['statusCode'] == null ? undefined : BusinessRestExceptionStatusCodeFromJSON(json['statusCode']),
        'detailMessageArguments': json['detailMessageArguments'] == null ? undefined : json['detailMessageArguments'],
        'detailMessageCode': json['detailMessageCode'] == null ? undefined : json['detailMessageCode'],
        'type': json['type'] == null ? undefined : json['type'],
        'typeMessageCode': json['typeMessageCode'] == null ? undefined : json['typeMessageCode'],
        'titleMessageCode': json['titleMessageCode'] == null ? undefined : json['titleMessageCode'],
        'rootCause': json['rootCause'] == null ? undefined : BusinessRestExceptionRootCauseFromJSON(json['rootCause']),
        'mostSpecificCause': json['mostSpecificCause'] == null ? undefined : BusinessRestExceptionCauseFromJSON(json['mostSpecificCause']),
        'suppressed': json['suppressed'] == null ? undefined : ((json['suppressed'] as Array<any>).map(BusinessRestExceptionCauseFromJSON)),
        'localizedMessage': json['localizedMessage'] == null ? undefined : json['localizedMessage'],
    };
}

export function BusinessRestExceptionToJSON(json: any): BusinessRestException {
    return BusinessRestExceptionToJSONTyped(json, false);
}

export function BusinessRestExceptionToJSONTyped(value?: BusinessRestException | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cause': BusinessRestExceptionCauseToJSON(value['cause']),
        'stackTrace': value['stackTrace'] == null ? undefined : ((value['stackTrace'] as Array<any>).map(BusinessRestExceptionCauseStackTraceInnerToJSON)),
        'headers': BusinessRestExceptionHeadersToJSON(value['headers']),
        'body': ProblemDetailToJSON(value['body']),
        'reason': value['reason'],
        'code': value['code'],
        'message': value['message'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(CodeMessageToJSON)),
        'responseHeaders': HttpHeadersToJSON(value['responseHeaders']),
        'detail': value['detail'],
        'title': value['title'],
        'instance': value['instance'],
        'statusCode': BusinessRestExceptionStatusCodeToJSON(value['statusCode']),
        'detailMessageArguments': value['detailMessageArguments'],
        'detailMessageCode': value['detailMessageCode'],
        'type': value['type'],
        'typeMessageCode': value['typeMessageCode'],
        'titleMessageCode': value['titleMessageCode'],
        'rootCause': BusinessRestExceptionRootCauseToJSON(value['rootCause']),
        'mostSpecificCause': BusinessRestExceptionCauseToJSON(value['mostSpecificCause']),
        'suppressed': value['suppressed'] == null ? undefined : ((value['suppressed'] as Array<any>).map(BusinessRestExceptionCauseToJSON)),
        'localizedMessage': value['localizedMessage'],
    };
}

