/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessRestExceptionHeadersHostAddress } from './BusinessRestExceptionHeadersHostAddress';
import {
    BusinessRestExceptionHeadersHostAddressFromJSON,
    BusinessRestExceptionHeadersHostAddressFromJSONTyped,
    BusinessRestExceptionHeadersHostAddressToJSON,
    BusinessRestExceptionHeadersHostAddressToJSONTyped,
} from './BusinessRestExceptionHeadersHostAddress';

/**
 * 
 * @export
 * @interface BusinessRestExceptionHeadersHost
 */
export interface BusinessRestExceptionHeadersHost {
    /**
     * 
     * @type {BusinessRestExceptionHeadersHostAddress}
     * @memberof BusinessRestExceptionHeadersHost
     */
    address?: BusinessRestExceptionHeadersHostAddress;
    /**
     * 
     * @type {number}
     * @memberof BusinessRestExceptionHeadersHost
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestExceptionHeadersHost
     */
    hostName?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRestExceptionHeadersHost
     */
    hostString?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessRestExceptionHeadersHost
     */
    unresolved?: boolean;
}

/**
 * Check if a given object implements the BusinessRestExceptionHeadersHost interface.
 */
export function instanceOfBusinessRestExceptionHeadersHost(value: object): value is BusinessRestExceptionHeadersHost {
    return true;
}

export function BusinessRestExceptionHeadersHostFromJSON(json: any): BusinessRestExceptionHeadersHost {
    return BusinessRestExceptionHeadersHostFromJSONTyped(json, false);
}

export function BusinessRestExceptionHeadersHostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRestExceptionHeadersHost {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : BusinessRestExceptionHeadersHostAddressFromJSON(json['address']),
        'port': json['port'] == null ? undefined : json['port'],
        'hostName': json['hostName'] == null ? undefined : json['hostName'],
        'hostString': json['hostString'] == null ? undefined : json['hostString'],
        'unresolved': json['unresolved'] == null ? undefined : json['unresolved'],
    };
}

export function BusinessRestExceptionHeadersHostToJSON(json: any): BusinessRestExceptionHeadersHost {
    return BusinessRestExceptionHeadersHostToJSONTyped(json, false);
}

export function BusinessRestExceptionHeadersHostToJSONTyped(value?: BusinessRestExceptionHeadersHost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': BusinessRestExceptionHeadersHostAddressToJSON(value['address']),
        'port': value['port'],
        'hostName': value['hostName'],
        'hostString': value['hostString'],
        'unresolved': value['unresolved'],
    };
}

