/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessRestExceptionHeadersAcceptLanguageInner
 */
export interface BusinessRestExceptionHeadersAcceptLanguageInner {
    /**
     * 
     * @type {string}
     * @memberof BusinessRestExceptionHeadersAcceptLanguageInner
     */
    range?: string;
    /**
     * 
     * @type {number}
     * @memberof BusinessRestExceptionHeadersAcceptLanguageInner
     */
    weight?: number;
}

/**
 * Check if a given object implements the BusinessRestExceptionHeadersAcceptLanguageInner interface.
 */
export function instanceOfBusinessRestExceptionHeadersAcceptLanguageInner(value: object): value is BusinessRestExceptionHeadersAcceptLanguageInner {
    return true;
}

export function BusinessRestExceptionHeadersAcceptLanguageInnerFromJSON(json: any): BusinessRestExceptionHeadersAcceptLanguageInner {
    return BusinessRestExceptionHeadersAcceptLanguageInnerFromJSONTyped(json, false);
}

export function BusinessRestExceptionHeadersAcceptLanguageInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRestExceptionHeadersAcceptLanguageInner {
    if (json == null) {
        return json;
    }
    return {
        
        'range': json['range'] == null ? undefined : json['range'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function BusinessRestExceptionHeadersAcceptLanguageInnerToJSON(json: any): BusinessRestExceptionHeadersAcceptLanguageInner {
    return BusinessRestExceptionHeadersAcceptLanguageInnerToJSONTyped(json, false);
}

export function BusinessRestExceptionHeadersAcceptLanguageInnerToJSONTyped(value?: BusinessRestExceptionHeadersAcceptLanguageInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'range': value['range'],
        'weight': value['weight'],
    };
}

