/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonSelectOfferParameters
 */
export interface CommonSelectOfferParameters {
    /**
     * 
     * @type {string}
     * @memberof CommonSelectOfferParameters
     */
    cashTransferAccountId?: string;
}

/**
 * Check if a given object implements the CommonSelectOfferParameters interface.
 */
export function instanceOfCommonSelectOfferParameters(value: object): value is CommonSelectOfferParameters {
    return true;
}

export function CommonSelectOfferParametersFromJSON(json: any): CommonSelectOfferParameters {
    return CommonSelectOfferParametersFromJSONTyped(json, false);
}

export function CommonSelectOfferParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSelectOfferParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'cashTransferAccountId': json['cashTransferAccountId'] == null ? undefined : json['cashTransferAccountId'],
    };
}

export function CommonSelectOfferParametersToJSON(json: any): CommonSelectOfferParameters {
    return CommonSelectOfferParametersToJSONTyped(json, false);
}

export function CommonSelectOfferParametersToJSONTyped(value?: CommonSelectOfferParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cashTransferAccountId': value['cashTransferAccountId'],
    };
}

