/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscardRequest
 */
export interface DiscardRequest {
    /**
     * 
     * @type {string}
     * @memberof DiscardRequest
     */
    reason: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscardRequest
     */
    accruedFeeIds?: Array<string>;
}

/**
 * Check if a given object implements the DiscardRequest interface.
 */
export function instanceOfDiscardRequest(value: object): value is DiscardRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function DiscardRequestFromJSON(json: any): DiscardRequest {
    return DiscardRequestFromJSONTyped(json, false);
}

export function DiscardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'accruedFeeIds': json['accruedFeeIds'] == null ? undefined : json['accruedFeeIds'],
    };
}

export function DiscardRequestToJSON(json: any): DiscardRequest {
    return DiscardRequestToJSONTyped(json, false);
}

export function DiscardRequestToJSONTyped(value?: DiscardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'accruedFeeIds': value['accruedFeeIds'],
    };
}

