/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EarlyRepaymentTermsResponse
 */
export interface EarlyRepaymentTermsResponse {
    /**
     * 
     * @type {number}
     * @memberof EarlyRepaymentTermsResponse
     */
    amountToRepay?: number;
    /**
     * 
     * @type {number}
     * @memberof EarlyRepaymentTermsResponse
     */
    discount?: number;
}

/**
 * Check if a given object implements the EarlyRepaymentTermsResponse interface.
 */
export function instanceOfEarlyRepaymentTermsResponse(value: object): value is EarlyRepaymentTermsResponse {
    return true;
}

export function EarlyRepaymentTermsResponseFromJSON(json: any): EarlyRepaymentTermsResponse {
    return EarlyRepaymentTermsResponseFromJSONTyped(json, false);
}

export function EarlyRepaymentTermsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EarlyRepaymentTermsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amountToRepay': json['amountToRepay'] == null ? undefined : json['amountToRepay'],
        'discount': json['discount'] == null ? undefined : json['discount'],
    };
}

export function EarlyRepaymentTermsResponseToJSON(json: any): EarlyRepaymentTermsResponse {
    return EarlyRepaymentTermsResponseToJSONTyped(json, false);
}

export function EarlyRepaymentTermsResponseToJSONTyped(value?: EarlyRepaymentTermsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amountToRepay': value['amountToRepay'],
        'discount': value['discount'],
    };
}

