/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoricalTransaction
 */
export interface HistoricalTransaction {
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    transRef?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    reversalRef?: string;
    /**
     * 
     * @type {Date}
     * @memberof HistoricalTransaction
     */
    transactionDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    transactionAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalTransaction
     */
    paymentMethod?: string;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    principal?: number;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    interest?: number;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    fees?: number;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    lateCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    suspense?: number;
    /**
     * 
     * @type {number}
     * @memberof HistoricalTransaction
     */
    principalBalance?: number;
}

/**
 * Check if a given object implements the HistoricalTransaction interface.
 */
export function instanceOfHistoricalTransaction(value: object): value is HistoricalTransaction {
    return true;
}

export function HistoricalTransactionFromJSON(json: any): HistoricalTransaction {
    return HistoricalTransactionFromJSONTyped(json, false);
}

export function HistoricalTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoricalTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'transRef': json['transRef'] == null ? undefined : json['transRef'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'reversalRef': json['reversalRef'] == null ? undefined : json['reversalRef'],
        'transactionDate': json['transactionDate'] == null ? undefined : (new Date(json['transactionDate'])),
        'transactionAmount': json['transactionAmount'] == null ? undefined : json['transactionAmount'],
        'description': json['description'] == null ? undefined : json['description'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'principal': json['principal'] == null ? undefined : json['principal'],
        'interest': json['interest'] == null ? undefined : json['interest'],
        'fees': json['fees'] == null ? undefined : json['fees'],
        'lateCharges': json['late_charges'] == null ? undefined : json['late_charges'],
        'suspense': json['suspense'] == null ? undefined : json['suspense'],
        'principalBalance': json['principalBalance'] == null ? undefined : json['principalBalance'],
    };
}

export function HistoricalTransactionToJSON(json: any): HistoricalTransaction {
    return HistoricalTransactionToJSONTyped(json, false);
}

export function HistoricalTransactionToJSONTyped(value?: HistoricalTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organisationId': value['organisationId'],
        'transRef': value['transRef'],
        'ref': value['ref'],
        'reversalRef': value['reversalRef'],
        'transactionDate': value['transactionDate'] == null ? undefined : ((value['transactionDate']).toISOString().substring(0,10)),
        'transactionAmount': value['transactionAmount'],
        'description': value['description'],
        'paymentMethod': value['paymentMethod'],
        'principal': value['principal'],
        'interest': value['interest'],
        'fees': value['fees'],
        'late_charges': value['lateCharges'],
        'suspense': value['suspense'],
        'principalBalance': value['principalBalance'],
    };
}

