/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LateFeeResponse } from './LateFeeResponse';
import {
    LateFeeResponseFromJSON,
    LateFeeResponseFromJSONTyped,
    LateFeeResponseToJSON,
    LateFeeResponseToJSONTyped,
} from './LateFeeResponse';

/**
 * 
 * @export
 * @interface LateFees
 */
export interface LateFees {
    /**
     * 
     * @type {Array<LateFeeResponse>}
     * @memberof LateFees
     */
    content?: Array<LateFeeResponse>;
}

/**
 * Check if a given object implements the LateFees interface.
 */
export function instanceOfLateFees(value: object): value is LateFees {
    return true;
}

export function LateFeesFromJSON(json: any): LateFees {
    return LateFeesFromJSONTyped(json, false);
}

export function LateFeesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LateFees {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(LateFeeResponseFromJSON)),
    };
}

export function LateFeesToJSON(json: any): LateFees {
    return LateFeesToJSONTyped(json, false);
}

export function LateFeesToJSONTyped(value?: LateFees | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(LateFeeResponseToJSON)),
    };
}

