/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineOfCreditOfferDetails
 */
export interface LineOfCreditOfferDetails {
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    totalAdvanceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    facilityFee?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    setupFee?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    drawDownTerm?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    drawRepaymentDurationMinimum?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    drawRepaymentDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    drawMinimumAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    drawFee?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    maxAdvanceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    maxRepaymentLength?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    minAdvanceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    minRepaymentLength?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    minBaseFee?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    firstDrawAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    firstDrawRepaymentDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof LineOfCreditOfferDetails
     */
    firstDrawFee?: number;
    /**
     * 
     * @type {string}
     * @memberof LineOfCreditOfferDetails
     * @deprecated
     */
    drawDocumentId?: string;
    /**
     * 
     * @type {string}
     * @memberof LineOfCreditOfferDetails
     */
    setupFeeCondition?: string;
    /**
     * 
     * @type {string}
     * @memberof LineOfCreditOfferDetails
     */
    securityFilings?: string;
    /**
     * 
     * @type {string}
     * @memberof LineOfCreditOfferDetails
     */
    reportingRequirements?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LineOfCreditOfferDetails
     */
    financialCovenants?: Array<string>;
}

/**
 * Check if a given object implements the LineOfCreditOfferDetails interface.
 */
export function instanceOfLineOfCreditOfferDetails(value: object): value is LineOfCreditOfferDetails {
    return true;
}

export function LineOfCreditOfferDetailsFromJSON(json: any): LineOfCreditOfferDetails {
    return LineOfCreditOfferDetailsFromJSONTyped(json, false);
}

export function LineOfCreditOfferDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineOfCreditOfferDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'totalAdvanceAmount': json['totalAdvanceAmount'] == null ? undefined : json['totalAdvanceAmount'],
        'facilityFee': json['facilityFee'] == null ? undefined : json['facilityFee'],
        'setupFee': json['setupFee'] == null ? undefined : json['setupFee'],
        'drawDownTerm': json['drawDownTerm'] == null ? undefined : json['drawDownTerm'],
        'drawRepaymentDurationMinimum': json['drawRepaymentDurationMinimum'] == null ? undefined : json['drawRepaymentDurationMinimum'],
        'drawRepaymentDuration': json['drawRepaymentDuration'] == null ? undefined : json['drawRepaymentDuration'],
        'drawMinimumAmount': json['drawMinimumAmount'] == null ? undefined : json['drawMinimumAmount'],
        'drawFee': json['drawFee'] == null ? undefined : json['drawFee'],
        'maxAdvanceAmount': json['maxAdvanceAmount'] == null ? undefined : json['maxAdvanceAmount'],
        'maxRepaymentLength': json['maxRepaymentLength'] == null ? undefined : json['maxRepaymentLength'],
        'minAdvanceAmount': json['minAdvanceAmount'] == null ? undefined : json['minAdvanceAmount'],
        'minRepaymentLength': json['minRepaymentLength'] == null ? undefined : json['minRepaymentLength'],
        'minBaseFee': json['minBaseFee'] == null ? undefined : json['minBaseFee'],
        'firstDrawAmount': json['firstDrawAmount'] == null ? undefined : json['firstDrawAmount'],
        'firstDrawRepaymentDuration': json['firstDrawRepaymentDuration'] == null ? undefined : json['firstDrawRepaymentDuration'],
        'firstDrawFee': json['firstDrawFee'] == null ? undefined : json['firstDrawFee'],
        'drawDocumentId': json['drawDocumentId'] == null ? undefined : json['drawDocumentId'],
        'setupFeeCondition': json['setupFeeCondition'] == null ? undefined : json['setupFeeCondition'],
        'securityFilings': json['securityFilings'] == null ? undefined : json['securityFilings'],
        'reportingRequirements': json['reportingRequirements'] == null ? undefined : json['reportingRequirements'],
        'financialCovenants': json['financialCovenants'] == null ? undefined : json['financialCovenants'],
    };
}

export function LineOfCreditOfferDetailsToJSON(json: any): LineOfCreditOfferDetails {
    return LineOfCreditOfferDetailsToJSONTyped(json, false);
}

export function LineOfCreditOfferDetailsToJSONTyped(value?: LineOfCreditOfferDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalAdvanceAmount': value['totalAdvanceAmount'],
        'facilityFee': value['facilityFee'],
        'setupFee': value['setupFee'],
        'drawDownTerm': value['drawDownTerm'],
        'drawRepaymentDurationMinimum': value['drawRepaymentDurationMinimum'],
        'drawRepaymentDuration': value['drawRepaymentDuration'],
        'drawMinimumAmount': value['drawMinimumAmount'],
        'drawFee': value['drawFee'],
        'maxAdvanceAmount': value['maxAdvanceAmount'],
        'maxRepaymentLength': value['maxRepaymentLength'],
        'minAdvanceAmount': value['minAdvanceAmount'],
        'minRepaymentLength': value['minRepaymentLength'],
        'minBaseFee': value['minBaseFee'],
        'firstDrawAmount': value['firstDrawAmount'],
        'firstDrawRepaymentDuration': value['firstDrawRepaymentDuration'],
        'firstDrawFee': value['firstDrawFee'],
        'drawDocumentId': value['drawDocumentId'],
        'setupFeeCondition': value['setupFeeCondition'],
        'securityFilings': value['securityFilings'],
        'reportingRequirements': value['reportingRequirements'],
        'financialCovenants': value['financialCovenants'],
    };
}

