/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeyTermResponse } from './KeyTermResponse';
import {
    KeyTermResponseFromJSON,
    KeyTermResponseFromJSONTyped,
    KeyTermResponseToJSON,
    KeyTermResponseToJSONTyped,
} from './KeyTermResponse';
import type { AgreementTerms } from './AgreementTerms';
import {
    AgreementTermsFromJSON,
    AgreementTermsFromJSONTyped,
    AgreementTermsToJSON,
    AgreementTermsToJSONTyped,
} from './AgreementTerms';

/**
 * 
 * @export
 * @interface OrganisationTermsResponse
 */
export interface OrganisationTermsResponse {
    /**
     * 
     * @type {Array<AgreementTerms>}
     * @memberof OrganisationTermsResponse
     */
    agreementTerms?: Array<AgreementTerms>;
    /**
     * 
     * @type {Array<KeyTermResponse>}
     * @memberof OrganisationTermsResponse
     */
    globalTerms?: Array<KeyTermResponse>;
}

/**
 * Check if a given object implements the OrganisationTermsResponse interface.
 */
export function instanceOfOrganisationTermsResponse(value: object): value is OrganisationTermsResponse {
    return true;
}

export function OrganisationTermsResponseFromJSON(json: any): OrganisationTermsResponse {
    return OrganisationTermsResponseFromJSONTyped(json, false);
}

export function OrganisationTermsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationTermsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementTerms': json['agreementTerms'] == null ? undefined : ((json['agreementTerms'] as Array<any>).map(AgreementTermsFromJSON)),
        'globalTerms': json['globalTerms'] == null ? undefined : ((json['globalTerms'] as Array<any>).map(KeyTermResponseFromJSON)),
    };
}

export function OrganisationTermsResponseToJSON(json: any): OrganisationTermsResponse {
    return OrganisationTermsResponseToJSONTyped(json, false);
}

export function OrganisationTermsResponseToJSONTyped(value?: OrganisationTermsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreementTerms': value['agreementTerms'] == null ? undefined : ((value['agreementTerms'] as Array<any>).map(AgreementTermsToJSON)),
        'globalTerms': value['globalTerms'] == null ? undefined : ((value['globalTerms'] as Array<any>).map(KeyTermResponseToJSON)),
    };
}

