/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchOfferRequest
 */
export interface PatchOfferRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchOfferRequest
     */
    cashTransferAccountId?: string;
}

/**
 * Check if a given object implements the PatchOfferRequest interface.
 */
export function instanceOfPatchOfferRequest(value: object): value is PatchOfferRequest {
    return true;
}

export function PatchOfferRequestFromJSON(json: any): PatchOfferRequest {
    return PatchOfferRequestFromJSONTyped(json, false);
}

export function PatchOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchOfferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cashTransferAccountId': json['cashTransferAccountId'] == null ? undefined : json['cashTransferAccountId'],
    };
}

export function PatchOfferRequestToJSON(json: any): PatchOfferRequest {
    return PatchOfferRequestToJSONTyped(json, false);
}

export function PatchOfferRequestToJSONTyped(value?: PatchOfferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cashTransferAccountId': value['cashTransferAccountId'],
    };
}

