/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeriodicRevenueStatsForPlatform
 */
export interface PeriodicRevenueStatsForPlatform {
    /**
     * 
     * @type {string}
     * @memberof PeriodicRevenueStatsForPlatform
     */
    platformName?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriodicRevenueStatsForPlatform
     */
    sourceType?: PeriodicRevenueStatsForPlatformSourceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PeriodicRevenueStatsForPlatform
     */
    averageRevenueInPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof PeriodicRevenueStatsForPlatform
     */
    months?: number;
}


/**
 * @export
 */
export const PeriodicRevenueStatsForPlatformSourceTypeEnum = {
    Ecommerce: 'ECOMMERCE',
    PaymentProcessor: 'PAYMENT_PROCESSOR',
    ManualEntry: 'MANUAL_ENTRY',
    Undefined: 'UNDEFINED'
} as const;
export type PeriodicRevenueStatsForPlatformSourceTypeEnum = typeof PeriodicRevenueStatsForPlatformSourceTypeEnum[keyof typeof PeriodicRevenueStatsForPlatformSourceTypeEnum];


/**
 * Check if a given object implements the PeriodicRevenueStatsForPlatform interface.
 */
export function instanceOfPeriodicRevenueStatsForPlatform(value: object): value is PeriodicRevenueStatsForPlatform {
    return true;
}

export function PeriodicRevenueStatsForPlatformFromJSON(json: any): PeriodicRevenueStatsForPlatform {
    return PeriodicRevenueStatsForPlatformFromJSONTyped(json, false);
}

export function PeriodicRevenueStatsForPlatformFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodicRevenueStatsForPlatform {
    if (json == null) {
        return json;
    }
    return {
        
        'platformName': json['platformName'] == null ? undefined : json['platformName'],
        'sourceType': json['sourceType'] == null ? undefined : json['sourceType'],
        'averageRevenueInPeriod': json['averageRevenueInPeriod'] == null ? undefined : json['averageRevenueInPeriod'],
        'months': json['months'] == null ? undefined : json['months'],
    };
}

export function PeriodicRevenueStatsForPlatformToJSON(json: any): PeriodicRevenueStatsForPlatform {
    return PeriodicRevenueStatsForPlatformToJSONTyped(json, false);
}

export function PeriodicRevenueStatsForPlatformToJSONTyped(value?: PeriodicRevenueStatsForPlatform | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platformName': value['platformName'],
        'sourceType': value['sourceType'],
        'averageRevenueInPeriod': value['averageRevenueInPeriod'],
        'months': value['months'],
    };
}

