/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestructureOfferDetails
 */
export interface RestructureOfferDetails {
    /**
     * 
     * @type {string}
     * @memberof RestructureOfferDetails
     */
    restructuredAgreementId?: string;
    /**
     * 
     * @type {string}
     * @memberof RestructureOfferDetails
     */
    repaymentScheduleDraftId?: string;
}

/**
 * Check if a given object implements the RestructureOfferDetails interface.
 */
export function instanceOfRestructureOfferDetails(value: object): value is RestructureOfferDetails {
    return true;
}

export function RestructureOfferDetailsFromJSON(json: any): RestructureOfferDetails {
    return RestructureOfferDetailsFromJSONTyped(json, false);
}

export function RestructureOfferDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestructureOfferDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'restructuredAgreementId': json['restructuredAgreementId'] == null ? undefined : json['restructuredAgreementId'],
        'repaymentScheduleDraftId': json['repaymentScheduleDraftId'] == null ? undefined : json['repaymentScheduleDraftId'],
    };
}

export function RestructureOfferDetailsToJSON(json: any): RestructureOfferDetails {
    return RestructureOfferDetailsToJSONTyped(json, false);
}

export function RestructureOfferDetailsToJSONTyped(value?: RestructureOfferDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restructuredAgreementId': value['restructuredAgreementId'],
        'repaymentScheduleDraftId': value['repaymentScheduleDraftId'],
    };
}

