/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LineOfCreditParameters } from './LineOfCreditParameters';
import {
    LineOfCreditParametersFromJSON,
    LineOfCreditParametersFromJSONTyped,
    LineOfCreditParametersToJSON,
    LineOfCreditParametersToJSONTyped,
} from './LineOfCreditParameters';
import type { CommonSelectOfferParameters } from './CommonSelectOfferParameters';
import {
    CommonSelectOfferParametersFromJSON,
    CommonSelectOfferParametersFromJSONTyped,
    CommonSelectOfferParametersToJSON,
    CommonSelectOfferParametersToJSONTyped,
} from './CommonSelectOfferParameters';
import type { CustomizableOfferParameters } from './CustomizableOfferParameters';
import {
    CustomizableOfferParametersFromJSON,
    CustomizableOfferParametersFromJSONTyped,
    CustomizableOfferParametersToJSON,
    CustomizableOfferParametersToJSONTyped,
} from './CustomizableOfferParameters';
import type { DeferredRepaymentsParameters } from './DeferredRepaymentsParameters';
import {
    DeferredRepaymentsParametersFromJSON,
    DeferredRepaymentsParametersFromJSONTyped,
    DeferredRepaymentsParametersToJSON,
    DeferredRepaymentsParametersToJSONTyped,
} from './DeferredRepaymentsParameters';
import type { InterestRateLineOfCreditParameters } from './InterestRateLineOfCreditParameters';
import {
    InterestRateLineOfCreditParametersFromJSON,
    InterestRateLineOfCreditParametersFromJSONTyped,
    InterestRateLineOfCreditParametersToJSON,
    InterestRateLineOfCreditParametersToJSONTyped,
} from './InterestRateLineOfCreditParameters';
import type { RbfOfferParameters } from './RbfOfferParameters';
import {
    RbfOfferParametersFromJSON,
    RbfOfferParametersFromJSONTyped,
    RbfOfferParametersToJSON,
    RbfOfferParametersToJSONTyped,
} from './RbfOfferParameters';

/**
 * 
 * @export
 * @interface SelectOfferRequest
 */
export interface SelectOfferRequest {
    /**
     * 
     * @type {CustomizableOfferParameters}
     * @memberof SelectOfferRequest
     */
    customizableOfferParameters?: CustomizableOfferParameters;
    /**
     * 
     * @type {LineOfCreditParameters}
     * @memberof SelectOfferRequest
     */
    lineOfCreditParameters?: LineOfCreditParameters;
    /**
     * 
     * @type {DeferredRepaymentsParameters}
     * @memberof SelectOfferRequest
     */
    deferredRepaymentsParameters?: DeferredRepaymentsParameters;
    /**
     * 
     * @type {CommonSelectOfferParameters}
     * @memberof SelectOfferRequest
     */
    commonSelectOfferParameters?: CommonSelectOfferParameters;
    /**
     * 
     * @type {InterestRateLineOfCreditParameters}
     * @memberof SelectOfferRequest
     */
    interestRateLineOfCreditParameters?: InterestRateLineOfCreditParameters;
    /**
     * 
     * @type {RbfOfferParameters}
     * @memberof SelectOfferRequest
     */
    rbfOfferParameters?: RbfOfferParameters;
}

/**
 * Check if a given object implements the SelectOfferRequest interface.
 */
export function instanceOfSelectOfferRequest(value: object): value is SelectOfferRequest {
    return true;
}

export function SelectOfferRequestFromJSON(json: any): SelectOfferRequest {
    return SelectOfferRequestFromJSONTyped(json, false);
}

export function SelectOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectOfferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customizableOfferParameters': json['customizableOfferParameters'] == null ? undefined : CustomizableOfferParametersFromJSON(json['customizableOfferParameters']),
        'lineOfCreditParameters': json['lineOfCreditParameters'] == null ? undefined : LineOfCreditParametersFromJSON(json['lineOfCreditParameters']),
        'deferredRepaymentsParameters': json['deferredRepaymentsParameters'] == null ? undefined : DeferredRepaymentsParametersFromJSON(json['deferredRepaymentsParameters']),
        'commonSelectOfferParameters': json['commonSelectOfferParameters'] == null ? undefined : CommonSelectOfferParametersFromJSON(json['commonSelectOfferParameters']),
        'interestRateLineOfCreditParameters': json['interestRateLineOfCreditParameters'] == null ? undefined : InterestRateLineOfCreditParametersFromJSON(json['interestRateLineOfCreditParameters']),
        'rbfOfferParameters': json['rbfOfferParameters'] == null ? undefined : RbfOfferParametersFromJSON(json['rbfOfferParameters']),
    };
}

export function SelectOfferRequestToJSON(json: any): SelectOfferRequest {
    return SelectOfferRequestToJSONTyped(json, false);
}

export function SelectOfferRequestToJSONTyped(value?: SelectOfferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customizableOfferParameters': CustomizableOfferParametersToJSON(value['customizableOfferParameters']),
        'lineOfCreditParameters': LineOfCreditParametersToJSON(value['lineOfCreditParameters']),
        'deferredRepaymentsParameters': DeferredRepaymentsParametersToJSON(value['deferredRepaymentsParameters']),
        'commonSelectOfferParameters': CommonSelectOfferParametersToJSON(value['commonSelectOfferParameters']),
        'interestRateLineOfCreditParameters': InterestRateLineOfCreditParametersToJSON(value['interestRateLineOfCreditParameters']),
        'rbfOfferParameters': RbfOfferParametersToJSON(value['rbfOfferParameters']),
    };
}

