/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupFeesDetails
 */
export interface SetupFeesDetails {
    /**
     * 
     * @type {string}
     * @memberof SetupFeesDetails
     */
    setupFeeType?: SetupFeesDetailsSetupFeeTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SetupFeesDetails
     */
    setupFeeDaysToCharge?: number;
    /**
     * 
     * @type {number}
     * @memberof SetupFeesDetails
     */
    setupFeeUtilizationPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof SetupFeesDetails
     */
    setupFeePercentOfMaxCreditLimit?: number;
}


/**
 * @export
 */
export const SetupFeesDetailsSetupFeeTypeEnum = {
    None: 'NONE',
    Unconditional: 'UNCONDITIONAL',
    Conditional: 'CONDITIONAL'
} as const;
export type SetupFeesDetailsSetupFeeTypeEnum = typeof SetupFeesDetailsSetupFeeTypeEnum[keyof typeof SetupFeesDetailsSetupFeeTypeEnum];


/**
 * Check if a given object implements the SetupFeesDetails interface.
 */
export function instanceOfSetupFeesDetails(value: object): value is SetupFeesDetails {
    return true;
}

export function SetupFeesDetailsFromJSON(json: any): SetupFeesDetails {
    return SetupFeesDetailsFromJSONTyped(json, false);
}

export function SetupFeesDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupFeesDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'setupFeeType': json['setupFeeType'] == null ? undefined : json['setupFeeType'],
        'setupFeeDaysToCharge': json['setupFeeDaysToCharge'] == null ? undefined : json['setupFeeDaysToCharge'],
        'setupFeeUtilizationPercent': json['setupFeeUtilizationPercent'] == null ? undefined : json['setupFeeUtilizationPercent'],
        'setupFeePercentOfMaxCreditLimit': json['setupFeePercentOfMaxCreditLimit'] == null ? undefined : json['setupFeePercentOfMaxCreditLimit'],
    };
}

export function SetupFeesDetailsToJSON(json: any): SetupFeesDetails {
    return SetupFeesDetailsToJSONTyped(json, false);
}

export function SetupFeesDetailsToJSONTyped(value?: SetupFeesDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'setupFeeType': value['setupFeeType'],
        'setupFeeDaysToCharge': value['setupFeeDaysToCharge'],
        'setupFeeUtilizationPercent': value['setupFeeUtilizationPercent'],
        'setupFeePercentOfMaxCreditLimit': value['setupFeePercentOfMaxCreditLimit'],
    };
}

