/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionAccount
 */
export interface TransactionAccount {
    /**
     * 
     * @type {string}
     * @memberof TransactionAccount
     */
    id: string;
}

/**
 * Check if a given object implements the TransactionAccount interface.
 */
export function instanceOfTransactionAccount(value: object): value is TransactionAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TransactionAccountFromJSON(json: any): TransactionAccount {
    return TransactionAccountFromJSONTyped(json, false);
}

export function TransactionAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TransactionAccountToJSON(json: any): TransactionAccount {
    return TransactionAccountToJSONTyped(json, false);
}

export function TransactionAccountToJSONTyped(value?: TransactionAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

