/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateIssueRequest
 */
export interface UpdateIssueRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    issueStatus?: UpdateIssueRequestIssueStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateIssueRequest
     */
    confidential?: boolean;
}


/**
 * @export
 */
export const UpdateIssueRequestIssueStatusEnum = {
    PoorPerformanceIdentified: 'POOR_PERFORMANCE_IDENTIFIED',
    BreachIdentified: 'BREACH_IDENTIFIED',
    CommunicationMode: 'COMMUNICATION_MODE',
    NegotiationUnderway: 'NEGOTIATION_UNDERWAY',
    NewAgreementClose: 'NEW_AGREEMENT_CLOSE',
    NewAgreementMonitor: 'NEW_AGREEMENT_MONITOR',
    NewManualAgreement: 'NEW_MANUAL_AGREEMENT',
    BreachOfContractNoticeSent: 'BREACH_OF_CONTRACT_NOTICE_SENT',
    DfrSent: 'DFR_SENT',
    LocalLawyersEngaged: 'LOCAL_LAWYERS_ENGAGED',
    Reported: 'REPORTED',
    Resolved: 'RESOLVED',
    MarkedAsIneligible: 'MARKED_AS_INELIGIBLE',
    AVeryGood: 'A_VERY_GOOD',
    BGood: 'B_GOOD',
    CWatchlist: 'C_WATCHLIST',
    DSubStandard: 'D_SUB_STANDARD',
    EDoubtful: 'E_DOUBTFUL',
    Unknown: 'UNKNOWN'
} as const;
export type UpdateIssueRequestIssueStatusEnum = typeof UpdateIssueRequestIssueStatusEnum[keyof typeof UpdateIssueRequestIssueStatusEnum];


/**
 * Check if a given object implements the UpdateIssueRequest interface.
 */
export function instanceOfUpdateIssueRequest(value: object): value is UpdateIssueRequest {
    return true;
}

export function UpdateIssueRequestFromJSON(json: any): UpdateIssueRequest {
    return UpdateIssueRequestFromJSONTyped(json, false);
}

export function UpdateIssueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIssueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'issueStatus': json['issueStatus'] == null ? undefined : json['issueStatus'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'confidential': json['confidential'] == null ? undefined : json['confidential'],
    };
}

export function UpdateIssueRequestToJSON(json: any): UpdateIssueRequest {
    return UpdateIssueRequestToJSONTyped(json, false);
}

export function UpdateIssueRequestToJSONTyped(value?: UpdateIssueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'issueStatus': value['issueStatus'],
        'comment': value['comment'],
        'confidential': value['confidential'],
    };
}

