/* tslint:disable */
/* eslint-disable */
/**
 * api-agreements
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateManualDefaultStatusRequest
 */
export interface UpdateManualDefaultStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateManualDefaultStatusRequest
     */
    agreementId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateManualDefaultStatusRequest
     */
    reason?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateManualDefaultStatusRequest
     */
    changeDate?: Date;
}

/**
 * Check if a given object implements the UpdateManualDefaultStatusRequest interface.
 */
export function instanceOfUpdateManualDefaultStatusRequest(value: object): value is UpdateManualDefaultStatusRequest {
    return true;
}

export function UpdateManualDefaultStatusRequestFromJSON(json: any): UpdateManualDefaultStatusRequest {
    return UpdateManualDefaultStatusRequestFromJSONTyped(json, false);
}

export function UpdateManualDefaultStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManualDefaultStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementId': json['agreementId'] == null ? undefined : json['agreementId'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'changeDate': json['changeDate'] == null ? undefined : (new Date(json['changeDate'])),
    };
}

export function UpdateManualDefaultStatusRequestToJSON(json: any): UpdateManualDefaultStatusRequest {
    return UpdateManualDefaultStatusRequestToJSONTyped(json, false);
}

export function UpdateManualDefaultStatusRequestToJSONTyped(value?: UpdateManualDefaultStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreementId': value['agreementId'],
        'reason': value['reason'],
        'changeDate': value['changeDate'] == null ? undefined : ((value['changeDate']).toISOString().substring(0,10)),
    };
}

