/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImpressionInteractionRequest,
  PortalImpressionUIResponse,
} from '../models/index';
import {
    ImpressionInteractionRequestFromJSON,
    ImpressionInteractionRequestToJSON,
    PortalImpressionUIResponseFromJSON,
    PortalImpressionUIResponseToJSON,
} from '../models/index';

export interface FindCurrentlyActiveRequest {
    xXORGID: string;
}

export interface FindImpressionRequest {
    impressionId: string;
    xXORGID: string;
}

export interface RecordImpressionInteractionRequest {
    impressionId: string;
    xXORGID: string;
    impressionInteractionRequest: ImpressionInteractionRequest;
}

/**
 * 
 */
export class CampaignInteractionControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async findCurrentlyActiveRaw(requestParameters: FindCurrentlyActiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortalImpressionUIResponse>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling findCurrentlyActive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/impressions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortalImpressionUIResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async findCurrentlyActive(requestParameters: FindCurrentlyActiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortalImpressionUIResponse> {
        const response = await this.findCurrentlyActiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async findImpressionRaw(requestParameters: FindImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortalImpressionUIResponse>> {
        if (requestParameters['impressionId'] == null) {
            throw new runtime.RequiredError(
                'impressionId',
                'Required parameter "impressionId" was null or undefined when calling findImpression().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling findImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/impressions/{impressionId}`;
        urlPath = urlPath.replace(`{${"impressionId"}}`, encodeURIComponent(String(requestParameters['impressionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortalImpressionUIResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async findImpression(requestParameters: FindImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortalImpressionUIResponse> {
        const response = await this.findImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async recordImpressionInteractionRaw(requestParameters: RecordImpressionInteractionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['impressionId'] == null) {
            throw new runtime.RequiredError(
                'impressionId',
                'Required parameter "impressionId" was null or undefined when calling recordImpressionInteraction().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling recordImpressionInteraction().'
            );
        }

        if (requestParameters['impressionInteractionRequest'] == null) {
            throw new runtime.RequiredError(
                'impressionInteractionRequest',
                'Required parameter "impressionInteractionRequest" was null or undefined when calling recordImpressionInteraction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/impressions/{impressionId}/interaction`;
        urlPath = urlPath.replace(`{${"impressionId"}}`, encodeURIComponent(String(requestParameters['impressionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpressionInteractionRequestToJSON(requestParameters['impressionInteractionRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async recordImpressionInteraction(requestParameters: RecordImpressionInteractionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordImpressionInteractionRaw(requestParameters, initOverrides);
    }

}
