/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EligibilityResponse,
} from '../models/index';
import {
    EligibilityResponseFromJSON,
    EligibilityResponseToJSON,
} from '../models/index';

export interface CheckTopUpEligibilityRequest {
    xXORGID: string;
}

/**
 * 
 */
export class EligibilityControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async checkTopUpEligibilityRaw(requestParameters: CheckTopUpEligibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EligibilityResponse>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling checkTopUpEligibility().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/eligibility/top-up`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EligibilityResponseFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async checkTopUpEligibility(requestParameters: CheckTopUpEligibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EligibilityResponse> {
        const response = await this.checkTopUpEligibilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
