/* tslint:disable */
/* eslint-disable */
/**
 * api-collections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SummaryDTO,
} from '../models/index';
import {
    SummaryDTOFromJSON,
    SummaryDTOToJSON,
} from '../models/index';

export interface GetSummaryRequest {
    xXORGID: string;
}

/**
 * 
 */
export class SummaryControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async getSummaryRaw(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SummaryDTO>>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getSummary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SummaryDTOFromJSON));
    }

    /**
     * This API requires **trusted** or **ORGROLE[SELF][admin]** role.
     */
    async getSummary(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SummaryDTO>> {
        const response = await this.getSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
