/* tslint:disable */
/* eslint-disable */
/**
 * amazon-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountLock,
  Application,
  CreditApproval,
  Loan,
  Offer,
  Repayment,
  RepaymentSchedule,
} from '../models/index';
import {
    AccountLockFromJSON,
    AccountLockToJSON,
    ApplicationFromJSON,
    ApplicationToJSON,
    CreditApprovalFromJSON,
    CreditApprovalToJSON,
    LoanFromJSON,
    LoanToJSON,
    OfferFromJSON,
    OfferToJSON,
    RepaymentFromJSON,
    RepaymentToJSON,
    RepaymentScheduleFromJSON,
    RepaymentScheduleToJSON,
} from '../models/index';

export interface AbandonApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface ApproveApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface CloseLoanRequest {
    loanId: string;
    xXORGID: string;
}

export interface ConfirmApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface ConfirmLockRequest {
    lockId: string;
    xXORGID: string;
}

export interface CreateApplicationRequest {
    xXORGID: string;
    application: Application;
}

export interface CreateCreditApprovalRequest {
    applicationId: string;
    xXORGID: string;
}

export interface CreateLoanRequest {
    creditApprovalId: string;
    xXORGID: string;
}

export interface CreateOfferRequest {
    offerAmount: number;
    xXORGID: string;
    productCode?: CreateOfferProductCodeEnum;
    merchant?: number;
}

export interface CreateRepaymentScheduleRequest {
    loanId: string;
    xXORGID: string;
    repayment: Array<Repayment>;
}

export interface GetApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface GetLoanRequest {
    loanId: string;
    xXORGID: string;
}

export interface GetLockAccountRequest {
    lockId: string;
    xXORGID: string;
}

export interface GetOfferRequest {
    offerId: string;
    xXORGID: string;
}

export interface GetRedirectUrlRequest {
    offerId: string;
    xXORGID: string;
}

export interface GetRepaymentScheduleRequest {
    scheduleId: string;
    xXORGID: string;
}

export interface InquiryOfferRequest {
    offerId: string;
    xXORGID: string;
}

export interface LockAccountRequest {
    applicationId: string;
    xXORGID: string;
}

export interface ReceiveApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface RejectApplicationRequest {
    applicationId: string;
    xXORGID: string;
}

export interface RemoveLockRequest {
    lockId: string;
    xXORGID: string;
}

export interface RestartFlowRequest {
    offerId: string;
    xXORGID: string;
    host?: string;
}

export interface StartFlowRequest {
    amount: number;
    apr: number;
    length: number;
    termUnit: StartFlowTermUnitEnum;
    xXORGID: string;
    authToken?: string;
    host?: string;
    productCode?: StartFlowProductCodeEnum;
    merchant?: number;
}

export interface UnlockLockRequest {
    lockId: string;
    xXORGID: string;
}

export interface UpdateApplicationRequest {
    xXORGID: string;
    application: Application;
}

export interface UpdateLoanRequest {
    xXORGID: string;
    loan: Loan;
}

/**
 * 
 */
export class TestFlowControllerApi extends runtime.BaseAPI {

    /**
     * This API requires **trusted** role.
     */
    async abandonApplicationRaw(requestParameters: AbandonApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling abandonApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling abandonApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/abandon`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async abandonApplication(requestParameters: AbandonApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.abandonApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async approveApplicationRaw(requestParameters: ApproveApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling approveApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling approveApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/approve`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async approveApplication(requestParameters: ApproveApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.approveApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async closeLoanRaw(requestParameters: CloseLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Loan>> {
        if (requestParameters['loanId'] == null) {
            throw new runtime.RequiredError(
                'loanId',
                'Required parameter "loanId" was null or undefined when calling closeLoan().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling closeLoan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/loan/{loanId}`;
        urlPath = urlPath.replace(`{${"loanId"}}`, encodeURIComponent(String(requestParameters['loanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async closeLoan(requestParameters: CloseLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Loan> {
        const response = await this.closeLoanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async confirmApplicationRaw(requestParameters: ConfirmApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling confirmApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling confirmApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/confirm`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async confirmApplication(requestParameters: ConfirmApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.confirmApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async confirmLockRaw(requestParameters: ConfirmLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLock>> {
        if (requestParameters['lockId'] == null) {
            throw new runtime.RequiredError(
                'lockId',
                'Required parameter "lockId" was null or undefined when calling confirmLock().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling confirmLock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/lock/{lockId}/confirm`;
        urlPath = urlPath.replace(`{${"lockId"}}`, encodeURIComponent(String(requestParameters['lockId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLockFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async confirmLock(requestParameters: ConfirmLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLock> {
        const response = await this.confirmLockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async createApplicationRaw(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createApplication().'
            );
        }

        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling createApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationToJSON(requestParameters['application']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async createApplication(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.createApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async createCreditApprovalRaw(requestParameters: CreateCreditApprovalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditApproval>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling createCreditApproval().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createCreditApproval().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/approval/{applicationId}`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditApprovalFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async createCreditApproval(requestParameters: CreateCreditApprovalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditApproval> {
        const response = await this.createCreditApprovalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async createLoanRaw(requestParameters: CreateLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Loan>> {
        if (requestParameters['creditApprovalId'] == null) {
            throw new runtime.RequiredError(
                'creditApprovalId',
                'Required parameter "creditApprovalId" was null or undefined when calling createLoan().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createLoan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/loan/{creditApprovalId}`;
        urlPath = urlPath.replace(`{${"creditApprovalId"}}`, encodeURIComponent(String(requestParameters['creditApprovalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async createLoan(requestParameters: CreateLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Loan> {
        const response = await this.createLoanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async createOfferRaw(requestParameters: CreateOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        if (requestParameters['offerAmount'] == null) {
            throw new runtime.RequiredError(
                'offerAmount',
                'Required parameter "offerAmount" was null or undefined when calling createOffer().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createOffer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offerAmount'] != null) {
            queryParameters['offerAmount'] = requestParameters['offerAmount'];
        }

        if (requestParameters['productCode'] != null) {
            queryParameters['productCode'] = requestParameters['productCode'];
        }

        if (requestParameters['merchant'] != null) {
            queryParameters['merchant'] = requestParameters['merchant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/offer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** or **organisation admin** role.
     */
    async createOffer(requestParameters: CreateOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.createOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async createRepaymentScheduleRaw(requestParameters: CreateRepaymentScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepaymentSchedule>> {
        if (requestParameters['loanId'] == null) {
            throw new runtime.RequiredError(
                'loanId',
                'Required parameter "loanId" was null or undefined when calling createRepaymentSchedule().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling createRepaymentSchedule().'
            );
        }

        if (requestParameters['repayment'] == null) {
            throw new runtime.RequiredError(
                'repayment',
                'Required parameter "repayment" was null or undefined when calling createRepaymentSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/repayment-schedule/{loanId}`;
        urlPath = urlPath.replace(`{${"loanId"}}`, encodeURIComponent(String(requestParameters['loanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['repayment']!.map(RepaymentToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepaymentScheduleFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async createRepaymentSchedule(requestParameters: CreateRepaymentScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepaymentSchedule> {
        const response = await this.createRepaymentScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getApplicationRaw(requestParameters: GetApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling getApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getApplication(requestParameters: GetApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.getApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getLoanRaw(requestParameters: GetLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Loan>> {
        if (requestParameters['loanId'] == null) {
            throw new runtime.RequiredError(
                'loanId',
                'Required parameter "loanId" was null or undefined when calling getLoan().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getLoan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/loan/{loanId}`;
        urlPath = urlPath.replace(`{${"loanId"}}`, encodeURIComponent(String(requestParameters['loanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getLoan(requestParameters: GetLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Loan> {
        const response = await this.getLoanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getLockAccountRaw(requestParameters: GetLockAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLock>> {
        if (requestParameters['lockId'] == null) {
            throw new runtime.RequiredError(
                'lockId',
                'Required parameter "lockId" was null or undefined when calling getLockAccount().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getLockAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/lock/{lockId}`;
        urlPath = urlPath.replace(`{${"lockId"}}`, encodeURIComponent(String(requestParameters['lockId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLockFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getLockAccount(requestParameters: GetLockAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLock> {
        const response = await this.getLockAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getOfferRaw(requestParameters: GetOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        if (requestParameters['offerId'] == null) {
            throw new runtime.RequiredError(
                'offerId',
                'Required parameter "offerId" was null or undefined when calling getOffer().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/offer/{offerId}`;
        urlPath = urlPath.replace(`{${"offerId"}}`, encodeURIComponent(String(requestParameters['offerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getOffer(requestParameters: GetOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.getOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getRedirectUrlRaw(requestParameters: GetRedirectUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['offerId'] == null) {
            throw new runtime.RequiredError(
                'offerId',
                'Required parameter "offerId" was null or undefined when calling getRedirectUrl().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getRedirectUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/redirect/{offerId}`;
        urlPath = urlPath.replace(`{${"offerId"}}`, encodeURIComponent(String(requestParameters['offerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This API requires **trusted** role.
     */
    async getRedirectUrl(requestParameters: GetRedirectUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getRedirectUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async getRepaymentScheduleRaw(requestParameters: GetRepaymentScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepaymentSchedule>> {
        if (requestParameters['scheduleId'] == null) {
            throw new runtime.RequiredError(
                'scheduleId',
                'Required parameter "scheduleId" was null or undefined when calling getRepaymentSchedule().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling getRepaymentSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/repayment-schedule/{scheduleId}`;
        urlPath = urlPath.replace(`{${"scheduleId"}}`, encodeURIComponent(String(requestParameters['scheduleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepaymentScheduleFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async getRepaymentSchedule(requestParameters: GetRepaymentScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepaymentSchedule> {
        const response = await this.getRepaymentScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async inquiryOfferRaw(requestParameters: InquiryOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        if (requestParameters['offerId'] == null) {
            throw new runtime.RequiredError(
                'offerId',
                'Required parameter "offerId" was null or undefined when calling inquiryOffer().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling inquiryOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/offer/{offerId}/inquiry`;
        urlPath = urlPath.replace(`{${"offerId"}}`, encodeURIComponent(String(requestParameters['offerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async inquiryOffer(requestParameters: InquiryOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.inquiryOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async lockAccountRaw(requestParameters: LockAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling lockAccount().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling lockAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/lock`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async lockAccount(requestParameters: LockAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.lockAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async receiveApplicationRaw(requestParameters: ReceiveApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling receiveApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling receiveApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/receive`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async receiveApplication(requestParameters: ReceiveApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.receiveApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async rejectApplicationRaw(requestParameters: RejectApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling rejectApplication().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling rejectApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}/reject`;
        urlPath = urlPath.replace(`{${"applicationId"}}`, encodeURIComponent(String(requestParameters['applicationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async rejectApplication(requestParameters: RejectApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.rejectApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async removeLockRaw(requestParameters: RemoveLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLock>> {
        if (requestParameters['lockId'] == null) {
            throw new runtime.RequiredError(
                'lockId',
                'Required parameter "lockId" was null or undefined when calling removeLock().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling removeLock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/lock/{lockId}`;
        urlPath = urlPath.replace(`{${"lockId"}}`, encodeURIComponent(String(requestParameters['lockId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLockFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async removeLock(requestParameters: RemoveLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLock> {
        const response = await this.removeLockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API is **public**.
     */
    async restartFlowRaw(requestParameters: RestartFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['offerId'] == null) {
            throw new runtime.RequiredError(
                'offerId',
                'Required parameter "offerId" was null or undefined when calling restartFlow().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling restartFlow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['host'] != null) {
            queryParameters['host'] = requestParameters['host'];
        }

        if (requestParameters['offerId'] != null) {
            queryParameters['offerId'] = requestParameters['offerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/restart`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API is **public**.
     */
    async restartFlow(requestParameters: RestartFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restartFlowRaw(requestParameters, initOverrides);
    }

    /**
     * This API is **public**.
     */
    async startFlowRaw(requestParameters: StartFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling startFlow().'
            );
        }

        if (requestParameters['apr'] == null) {
            throw new runtime.RequiredError(
                'apr',
                'Required parameter "apr" was null or undefined when calling startFlow().'
            );
        }

        if (requestParameters['length'] == null) {
            throw new runtime.RequiredError(
                'length',
                'Required parameter "length" was null or undefined when calling startFlow().'
            );
        }

        if (requestParameters['termUnit'] == null) {
            throw new runtime.RequiredError(
                'termUnit',
                'Required parameter "termUnit" was null or undefined when calling startFlow().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling startFlow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        if (requestParameters['apr'] != null) {
            queryParameters['apr'] = requestParameters['apr'];
        }

        if (requestParameters['length'] != null) {
            queryParameters['length'] = requestParameters['length'];
        }

        if (requestParameters['termUnit'] != null) {
            queryParameters['termUnit'] = requestParameters['termUnit'];
        }

        if (requestParameters['authToken'] != null) {
            queryParameters['authToken'] = requestParameters['authToken'];
        }

        if (requestParameters['host'] != null) {
            queryParameters['host'] = requestParameters['host'];
        }

        if (requestParameters['productCode'] != null) {
            queryParameters['productCode'] = requestParameters['productCode'];
        }

        if (requestParameters['merchant'] != null) {
            queryParameters['merchant'] = requestParameters['merchant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/start`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This API is **public**.
     */
    async startFlow(requestParameters: StartFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startFlowRaw(requestParameters, initOverrides);
    }

    /**
     * This API requires **trusted** role.
     */
    async unlockLockRaw(requestParameters: UnlockLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLock>> {
        if (requestParameters['lockId'] == null) {
            throw new runtime.RequiredError(
                'lockId',
                'Required parameter "lockId" was null or undefined when calling unlockLock().'
            );
        }

        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling unlockLock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/lock/{lockId}/unlock`;
        urlPath = urlPath.replace(`{${"lockId"}}`, encodeURIComponent(String(requestParameters['lockId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLockFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async unlockLock(requestParameters: UnlockLockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLock> {
        const response = await this.unlockLockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async updateApplicationRaw(requestParameters: UpdateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling updateApplication().'
            );
        }

        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling updateApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/application/{applicationId}`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationToJSON(requestParameters['application']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async updateApplication(requestParameters: UpdateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.updateApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API requires **trusted** role.
     */
    async updateLoanRaw(requestParameters: UpdateLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Loan>> {
        if (requestParameters['xXORGID'] == null) {
            throw new runtime.RequiredError(
                'xXORGID',
                'Required parameter "xXORGID" was null or undefined when calling updateLoan().'
            );
        }

        if (requestParameters['loan'] == null) {
            throw new runtime.RequiredError(
                'loan',
                'Required parameter "loan" was null or undefined when calling updateLoan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xXORGID'] != null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters['xXORGID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", ["read", "write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/test-flow/loan`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LoanToJSON(requestParameters['loan']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanFromJSON(jsonValue));
    }

    /**
     * This API requires **trusted** role.
     */
    async updateLoan(requestParameters: UpdateLoanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Loan> {
        const response = await this.updateLoanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateOfferProductCodeEnum = {
    TermLoan: 'TERM_LOAN',
    LineOfCredit: 'LINE_OF_CREDIT'
} as const;
export type CreateOfferProductCodeEnum = typeof CreateOfferProductCodeEnum[keyof typeof CreateOfferProductCodeEnum];
/**
 * @export
 */
export const StartFlowTermUnitEnum = {
    Day: 'DAY',
    Week: 'WEEK',
    Month: 'MONTH'
} as const;
export type StartFlowTermUnitEnum = typeof StartFlowTermUnitEnum[keyof typeof StartFlowTermUnitEnum];
/**
 * @export
 */
export const StartFlowProductCodeEnum = {
    TermLoan: 'TERM_LOAN',
    LineOfCredit: 'LINE_OF_CREDIT'
} as const;
export type StartFlowProductCodeEnum = typeof StartFlowProductCodeEnum[keyof typeof StartFlowProductCodeEnum];
