/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignUploadErrorResponse
 */
export interface CampaignUploadErrorResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CampaignUploadErrorResponse
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the CampaignUploadErrorResponse interface.
 */
export function instanceOfCampaignUploadErrorResponse(value: object): value is CampaignUploadErrorResponse {
    return true;
}

export function CampaignUploadErrorResponseFromJSON(json: any): CampaignUploadErrorResponse {
    return CampaignUploadErrorResponseFromJSONTyped(json, false);
}

export function CampaignUploadErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignUploadErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function CampaignUploadErrorResponseToJSON(json: any): CampaignUploadErrorResponse {
    return CampaignUploadErrorResponseToJSONTyped(json, false);
}

export function CampaignUploadErrorResponseToJSONTyped(value?: CampaignUploadErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
    };
}

