/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EligibilityResponse
 */
export interface EligibilityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof EligibilityResponse
     */
    isEligible?: boolean;
}

/**
 * Check if a given object implements the EligibilityResponse interface.
 */
export function instanceOfEligibilityResponse(value: object): value is EligibilityResponse {
    return true;
}

export function EligibilityResponseFromJSON(json: any): EligibilityResponse {
    return EligibilityResponseFromJSONTyped(json, false);
}

export function EligibilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EligibilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isEligible': json['isEligible'] == null ? undefined : json['isEligible'],
    };
}

export function EligibilityResponseToJSON(json: any): EligibilityResponse {
    return EligibilityResponseToJSONTyped(json, false);
}

export function EligibilityResponseToJSONTyped(value?: EligibilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isEligible': value['isEligible'],
    };
}

