/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailImpressionResponse } from './EmailImpressionResponse';
import {
    EmailImpressionResponseFromJSON,
    EmailImpressionResponseFromJSONTyped,
    EmailImpressionResponseToJSON,
    EmailImpressionResponseToJSONTyped,
} from './EmailImpressionResponse';
import type { PortalImpressionResponse } from './PortalImpressionResponse';
import {
    PortalImpressionResponseFromJSON,
    PortalImpressionResponseFromJSONTyped,
    PortalImpressionResponseToJSON,
    PortalImpressionResponseToJSONTyped,
} from './PortalImpressionResponse';

/**
 * 
 * @export
 * @interface ImpressionsResponse
 */
export interface ImpressionsResponse {
    /**
     * 
     * @type {Array<EmailImpressionResponse>}
     * @memberof ImpressionsResponse
     */
    emailImpressions?: Array<EmailImpressionResponse>;
    /**
     * 
     * @type {Array<PortalImpressionResponse>}
     * @memberof ImpressionsResponse
     */
    portalImpressions?: Array<PortalImpressionResponse>;
}

/**
 * Check if a given object implements the ImpressionsResponse interface.
 */
export function instanceOfImpressionsResponse(value: object): value is ImpressionsResponse {
    return true;
}

export function ImpressionsResponseFromJSON(json: any): ImpressionsResponse {
    return ImpressionsResponseFromJSONTyped(json, false);
}

export function ImpressionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpressionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'emailImpressions': json['emailImpressions'] == null ? undefined : ((json['emailImpressions'] as Array<any>).map(EmailImpressionResponseFromJSON)),
        'portalImpressions': json['portalImpressions'] == null ? undefined : ((json['portalImpressions'] as Array<any>).map(PortalImpressionResponseFromJSON)),
    };
}

export function ImpressionsResponseToJSON(json: any): ImpressionsResponse {
    return ImpressionsResponseToJSONTyped(json, false);
}

export function ImpressionsResponseToJSONTyped(value?: ImpressionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emailImpressions': value['emailImpressions'] == null ? undefined : ((value['emailImpressions'] as Array<any>).map(EmailImpressionResponseToJSON)),
        'portalImpressions': value['portalImpressions'] == null ? undefined : ((value['portalImpressions'] as Array<any>).map(PortalImpressionResponseToJSON)),
    };
}

