/* tslint:disable */
/* eslint-disable */
/**
 * api-reengagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SegmentOrganisationResponse
 */
export interface SegmentOrganisationResponse {
    /**
     * 
     * @type {string}
     * @memberof SegmentOrganisationResponse
     */
    organisationId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SegmentOrganisationResponse
     */
    attributes?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SegmentOrganisationResponse interface.
 */
export function instanceOfSegmentOrganisationResponse(value: object): value is SegmentOrganisationResponse {
    return true;
}

export function SegmentOrganisationResponseFromJSON(json: any): SegmentOrganisationResponse {
    return SegmentOrganisationResponseFromJSONTyped(json, false);
}

export function SegmentOrganisationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentOrganisationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationId': json['organisationId'] == null ? undefined : json['organisationId'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function SegmentOrganisationResponseToJSON(json: any): SegmentOrganisationResponse {
    return SegmentOrganisationResponseToJSONTyped(json, false);
}

export function SegmentOrganisationResponseToJSONTyped(value?: SegmentOrganisationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisationId': value['organisationId'],
        'attributes': value['attributes'],
    };
}

