/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssociationDto
 */
export interface AssociationDto {
    /**
     * 
     * @type {string}
     * @memberof AssociationDto
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof AssociationDto
     */
    typeId?: number;
    /**
     * 
     * @type {string}
     * @memberof AssociationDto
     */
    label?: string;
}

/**
 * Check if a given object implements the AssociationDto interface.
 */
export function instanceOfAssociationDto(value: object): value is AssociationDto {
    return true;
}

export function AssociationDtoFromJSON(json: any): AssociationDto {
    return AssociationDtoFromJSONTyped(json, false);
}

export function AssociationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssociationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'typeId': json['typeId'] == null ? undefined : json['typeId'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function AssociationDtoToJSON(json: any): AssociationDto {
    return AssociationDtoToJSONTyped(json, false);
}

export function AssociationDtoToJSONTyped(value?: AssociationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'typeId': value['typeId'],
        'label': value['label'],
    };
}

