/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DealTag
 */
export interface DealTag {
    /**
     * 
     * @type {string}
     * @memberof DealTag
     */
    name?: DealTagNameEnum;
    /**
     * 
     * @type {string}
     * @memberof DealTag
     */
    value?: string;
}


/**
 * @export
 */
export const DealTagNameEnum = {
    UtmSource: 'UTM_SOURCE',
    UtmMedium: 'UTM_MEDIUM',
    UtmCampaign: 'UTM_CAMPAIGN',
    UtmTerm: 'UTM_TERM',
    UtmContent: 'UTM_CONTENT',
    UtmIntent: 'UTM_INTENT',
    UnknownTag: 'UNKNOWN_TAG'
} as const;
export type DealTagNameEnum = typeof DealTagNameEnum[keyof typeof DealTagNameEnum];


/**
 * Check if a given object implements the DealTag interface.
 */
export function instanceOfDealTag(value: object): value is DealTag {
    return true;
}

export function DealTagFromJSON(json: any): DealTag {
    return DealTagFromJSONTyped(json, false);
}

export function DealTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealTag {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DealTagToJSON(json: any): DealTag {
    return DealTagToJSONTyped(json, false);
}

export function DealTagToJSONTyped(value?: DealTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

