/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DealDecision
 */
export interface DealDecision {
    /**
     * 
     * @type {string}
     * @memberof DealDecision
     */
    decision?: DealDecisionDecisionEnum;
}


/**
 * @export
 */
export const DealDecisionDecisionEnum = {
    LowerOffer: 'LOWER_OFFER'
} as const;
export type DealDecisionDecisionEnum = typeof DealDecisionDecisionEnum[keyof typeof DealDecisionDecisionEnum];


/**
 * Check if a given object implements the DealDecision interface.
 */
export function instanceOfDealDecision(value: object): value is DealDecision {
    return true;
}

export function DealDecisionFromJSON(json: any): DealDecision {
    return DealDecisionFromJSONTyped(json, false);
}

export function DealDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealDecision {
    if (json == null) {
        return json;
    }
    return {
        
        'decision': json['decision'] == null ? undefined : json['decision'],
    };
}

export function DealDecisionToJSON(json: any): DealDecision {
    return DealDecisionToJSONTyped(json, false);
}

export function DealDecisionToJSONTyped(value?: DealDecision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decision': value['decision'],
    };
}

