/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonetaryAmount } from './MonetaryAmount';
import {
    MonetaryAmountFromJSON,
    MonetaryAmountFromJSONTyped,
    MonetaryAmountToJSON,
    MonetaryAmountToJSONTyped,
} from './MonetaryAmount';

/**
 * 
 * @export
 * @interface EligibilityData
 */
export interface EligibilityData {
    /**
     * 
     * @type {MonetaryAmount}
     * @memberof EligibilityData
     */
    averageMonthlyRevenue?: MonetaryAmount;
    /**
     * 
     * @type {boolean}
     * @memberof EligibilityData
     */
    isSoleTrader?: boolean;
    /**
     * 
     * @type {Set<string>}
     * @memberof EligibilityData
     */
    businessTypes?: Set<EligibilityDataBusinessTypesEnum>;
    /**
     * 
     * @type {MonetaryAmount}
     * @memberof EligibilityData
     */
    preliminaryOffer?: MonetaryAmount;
    /**
     * 
     * @type {string}
     * @memberof EligibilityData
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof EligibilityData
     */
    campaignReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof EligibilityData
     */
    parentDealId?: string;
}


/**
 * @export
 */
export const EligibilityDataBusinessTypesEnum = {
    EcommerceAmazonMarketplace: 'ECOMMERCE_AMAZON_MARKETPLACE',
    RetailWholesale: 'RETAIL_WHOLESALE',
    SubscriptionSaas: 'SUBSCRIPTION_SAAS',
    Other: 'OTHER'
} as const;
export type EligibilityDataBusinessTypesEnum = typeof EligibilityDataBusinessTypesEnum[keyof typeof EligibilityDataBusinessTypesEnum];


/**
 * Check if a given object implements the EligibilityData interface.
 */
export function instanceOfEligibilityData(value: object): value is EligibilityData {
    return true;
}

export function EligibilityDataFromJSON(json: any): EligibilityData {
    return EligibilityDataFromJSONTyped(json, false);
}

export function EligibilityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EligibilityData {
    if (json == null) {
        return json;
    }
    return {
        
        'averageMonthlyRevenue': json['averageMonthlyRevenue'] == null ? undefined : MonetaryAmountFromJSON(json['averageMonthlyRevenue']),
        'isSoleTrader': json['isSoleTrader'] == null ? undefined : json['isSoleTrader'],
        'businessTypes': json['businessTypes'] == null ? undefined : new Set(json['businessTypes']),
        'preliminaryOffer': json['preliminaryOffer'] == null ? undefined : MonetaryAmountFromJSON(json['preliminaryOffer']),
        'country': json['country'] == null ? undefined : json['country'],
        'campaignReferenceId': json['campaignReferenceId'] == null ? undefined : json['campaignReferenceId'],
        'parentDealId': json['parentDealId'] == null ? undefined : json['parentDealId'],
    };
}

export function EligibilityDataToJSON(json: any): EligibilityData {
    return EligibilityDataToJSONTyped(json, false);
}

export function EligibilityDataToJSONTyped(value?: EligibilityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'averageMonthlyRevenue': MonetaryAmountToJSON(value['averageMonthlyRevenue']),
        'isSoleTrader': value['isSoleTrader'],
        'businessTypes': value['businessTypes'] == null ? undefined : Array.from(value['businessTypes'] as Set<any>),
        'preliminaryOffer': MonetaryAmountToJSON(value['preliminaryOffer']),
        'country': value['country'],
        'campaignReferenceId': value['campaignReferenceId'],
        'parentDealId': value['parentDealId'],
    };
}

