/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LostDealRequest
 */
export interface LostDealRequest {
    /**
     * 
     * @type {Set<string>}
     * @memberof LostDealRequest
     */
    reasons: Set<LostDealRequestReasonsEnum>;
    /**
     * 
     * @type {string}
     * @memberof LostDealRequest
     */
    requestedBy: string;
}


/**
 * @export
 */
export const LostDealRequestReasonsEnum = {
    LostToAnotherProduct: 'LOST_TO_ANOTHER_PRODUCT',
    TopupNoImmediateFundingRequirement: 'TOPUP_NO_IMMEDIATE_FUNDING_REQUIREMENT',
    UnfinishedApplication: 'UNFINISHED_APPLICATION',
    OfferRejected: 'OFFER_REJECTED',
    UnsupportedBusinessModel: 'UNSUPPORTED_BUSINESS_MODEL',
    ClientWouldntRespond: 'CLIENT_WOULDNT_RESPOND',
    RejectedClientAfterAnalysis: 'REJECTED_CLIENT_AFTER_ANALYSIS',
    NotLookingForCapital: 'NOT_LOOKING_FOR_CAPITAL',
    PricingCouldNotAgreed: 'PRICING_COULD_NOT_AGREED',
    NoOfferClientNotConvinced: 'NO_OFFER_CLIENT_NOT_CONVINCED',
    BelowMinRevenueRequirement: 'BELOW_MIN_REVENUE_REQUIREMENT',
    CountryStateNotSupported: 'COUNTRY_STATE_NOT_SUPPORTED',
    LostToCompetitor: 'LOST_TO_COMPETITOR',
    ExistingCustomer: 'EXISTING_CUSTOMER',
    FakeTestSignUp: 'FAKE_TEST_SIGN_UP',
    UnableToShareData: 'UNABLE_TO_SHARE_DATA',
    RejectedAfterDueDiligence: 'REJECTED_AFTER_DUE_DILIGENCE',
    ShortTermLiquidity: 'SHORT_TERM_LIQUIDITY',
    TopupNotEligibleNow: 'TOPUP_NOT_ELIGIBLE_NOW',
    NotIcp: 'NOT_ICP'
} as const;
export type LostDealRequestReasonsEnum = typeof LostDealRequestReasonsEnum[keyof typeof LostDealRequestReasonsEnum];


/**
 * Check if a given object implements the LostDealRequest interface.
 */
export function instanceOfLostDealRequest(value: object): value is LostDealRequest {
    if (!('reasons' in value) || value['reasons'] === undefined) return false;
    if (!('requestedBy' in value) || value['requestedBy'] === undefined) return false;
    return true;
}

export function LostDealRequestFromJSON(json: any): LostDealRequest {
    return LostDealRequestFromJSONTyped(json, false);
}

export function LostDealRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LostDealRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reasons': new Set(json['reasons']),
        'requestedBy': json['requestedBy'],
    };
}

export function LostDealRequestToJSON(json: any): LostDealRequest {
    return LostDealRequestToJSONTyped(json, false);
}

export function LostDealRequestToJSONTyped(value?: LostDealRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reasons': Array.from(value['reasons'] as Set<any>),
        'requestedBy': value['requestedBy'],
    };
}

