/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineStageDto
 */
export interface PipelineStageDto {
    /**
     * 
     * @type {string}
     * @memberof PipelineStageDto
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof PipelineStageDto
     */
    displayOrder?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PipelineStageDto
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {Date}
     * @memberof PipelineStageDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PipelineStageDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PipelineStageDto
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PipelineStageDto
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PipelineStageDto
     */
    pipelineStageClosedTicket?: boolean;
}

/**
 * Check if a given object implements the PipelineStageDto interface.
 */
export function instanceOfPipelineStageDto(value: object): value is PipelineStageDto {
    return true;
}

export function PipelineStageDtoFromJSON(json: any): PipelineStageDto {
    return PipelineStageDtoFromJSONTyped(json, false);
}

export function PipelineStageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'archived': json['archived'] == null ? undefined : json['archived'],
        'id': json['id'] == null ? undefined : json['id'],
        'pipelineStageClosedTicket': json['pipelineStageClosedTicket'] == null ? undefined : json['pipelineStageClosedTicket'],
    };
}

export function PipelineStageDtoToJSON(json: any): PipelineStageDto {
    return PipelineStageDtoToJSONTyped(json, false);
}

export function PipelineStageDtoToJSONTyped(value?: PipelineStageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'displayOrder': value['displayOrder'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'archived': value['archived'],
        'id': value['id'],
        'pipelineStageClosedTicket': value['pipelineStageClosedTicket'],
    };
}

