/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReApplicationEligibilityResponse
 */
export interface ReApplicationEligibilityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ReApplicationEligibilityResponse
     */
    eligible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReApplicationEligibilityResponse
     */
    attribution?: ReApplicationEligibilityResponseAttributionEnum;
    /**
     * 
     * @type {Date}
     * @memberof ReApplicationEligibilityResponse
     */
    notEligibleTill?: Date;
}


/**
 * @export
 */
export const ReApplicationEligibilityResponseAttributionEnum = {
    Amazon: 'AMAZON',
    Uncapped: 'UNCAPPED',
    None: 'NONE'
} as const;
export type ReApplicationEligibilityResponseAttributionEnum = typeof ReApplicationEligibilityResponseAttributionEnum[keyof typeof ReApplicationEligibilityResponseAttributionEnum];


/**
 * Check if a given object implements the ReApplicationEligibilityResponse interface.
 */
export function instanceOfReApplicationEligibilityResponse(value: object): value is ReApplicationEligibilityResponse {
    return true;
}

export function ReApplicationEligibilityResponseFromJSON(json: any): ReApplicationEligibilityResponse {
    return ReApplicationEligibilityResponseFromJSONTyped(json, false);
}

export function ReApplicationEligibilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReApplicationEligibilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eligible': json['eligible'] == null ? undefined : json['eligible'],
        'attribution': json['attribution'] == null ? undefined : json['attribution'],
        'notEligibleTill': json['notEligibleTill'] == null ? undefined : (new Date(json['notEligibleTill'])),
    };
}

export function ReApplicationEligibilityResponseToJSON(json: any): ReApplicationEligibilityResponse {
    return ReApplicationEligibilityResponseToJSONTyped(json, false);
}

export function ReApplicationEligibilityResponseToJSONTyped(value?: ReApplicationEligibilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eligible': value['eligible'],
        'attribution': value['attribution'],
        'notEligibleTill': value['notEligibleTill'] == null ? undefined : ((value['notEligibleTill']).toISOString().substring(0,10)),
    };
}

