/* tslint:disable */
/* eslint-disable */
/**
 * hubspot-processor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonetaryAmount } from './MonetaryAmount';
import {
    MonetaryAmountFromJSON,
    MonetaryAmountFromJSONTyped,
    MonetaryAmountToJSON,
    MonetaryAmountToJSONTyped,
} from './MonetaryAmount';

/**
 * 
 * @export
 * @interface TopUpOnDemandRequest
 */
export interface TopUpOnDemandRequest {
    /**
     * 
     * @type {string}
     * @memberof TopUpOnDemandRequest
     */
    campaignReferenceId?: string;
    /**
     * 
     * @type {MonetaryAmount}
     * @memberof TopUpOnDemandRequest
     */
    amount: MonetaryAmount;
    /**
     * 
     * @type {string}
     * @memberof TopUpOnDemandRequest
     */
    parentDealId?: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpOnDemandRequest
     */
    tier?: TopUpOnDemandRequestTierEnum;
}


/**
 * @export
 */
export const TopUpOnDemandRequestTierEnum = {
    Small: 'SMALL',
    Big: 'BIG'
} as const;
export type TopUpOnDemandRequestTierEnum = typeof TopUpOnDemandRequestTierEnum[keyof typeof TopUpOnDemandRequestTierEnum];


/**
 * Check if a given object implements the TopUpOnDemandRequest interface.
 */
export function instanceOfTopUpOnDemandRequest(value: object): value is TopUpOnDemandRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TopUpOnDemandRequestFromJSON(json: any): TopUpOnDemandRequest {
    return TopUpOnDemandRequestFromJSONTyped(json, false);
}

export function TopUpOnDemandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopUpOnDemandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignReferenceId': json['campaignReferenceId'] == null ? undefined : json['campaignReferenceId'],
        'amount': MonetaryAmountFromJSON(json['amount']),
        'parentDealId': json['parentDealId'] == null ? undefined : json['parentDealId'],
        'tier': json['tier'] == null ? undefined : json['tier'],
    };
}

export function TopUpOnDemandRequestToJSON(json: any): TopUpOnDemandRequest {
    return TopUpOnDemandRequestToJSONTyped(json, false);
}

export function TopUpOnDemandRequestToJSONTyped(value?: TopUpOnDemandRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaignReferenceId': value['campaignReferenceId'],
        'amount': MonetaryAmountToJSON(value['amount']),
        'parentDealId': value['parentDealId'],
        'tier': value['tier'],
    };
}

