/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ConnectionTemplateDTO,
    ConnectionTemplateDTOFromJSON,
    ConnectionTemplateDTOToJSON,
    Property,
    PropertyFromJSON,
    PropertyToJSON,
} from '../models';

export interface Encrypt1Request {
    id: string;
    xXORGID: string;
    property: Property;
}

export interface GetConnectionTemplateRequest {
    id: string;
    xXORGID: string;
}

export interface GetConnectionTemplatesRequest {
    systemId: string;
    xXORGID: string;
}

/**
 * 
 */
export class ConnectionTemplateControllerApi extends runtime.BaseAPI {

    /**
     */
    async encrypt1Raw(requestParameters: Encrypt1Request, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling encrypt1.');
        }

        if (requestParameters.xXORGID === null || requestParameters.xXORGID === undefined) {
            throw new runtime.RequiredError('xXORGID','Required parameter requestParameters.xXORGID was null or undefined when calling encrypt1.');
        }

        if (requestParameters.property === null || requestParameters.property === undefined) {
            throw new runtime.RequiredError('property','Required parameter requestParameters.property was null or undefined when calling encrypt1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xXORGID !== undefined && requestParameters.xXORGID !== null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters.xXORGID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/connectionTemplates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PropertyToJSON(requestParameters.property),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async encrypt1(requestParameters: Encrypt1Request, initOverrides?: RequestInit): Promise<void> {
        await this.encrypt1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async getConnectionTemplateRaw(requestParameters: GetConnectionTemplateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConnectionTemplateDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getConnectionTemplate.');
        }

        if (requestParameters.xXORGID === null || requestParameters.xXORGID === undefined) {
            throw new runtime.RequiredError('xXORGID','Required parameter requestParameters.xXORGID was null or undefined when calling getConnectionTemplate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xXORGID !== undefined && requestParameters.xXORGID !== null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters.xXORGID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/connectionTemplates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionTemplateDTOFromJSON(jsonValue));
    }

    /**
     */
    async getConnectionTemplate(requestParameters: GetConnectionTemplateRequest, initOverrides?: RequestInit): Promise<ConnectionTemplateDTO> {
        const response = await this.getConnectionTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getConnectionTemplatesRaw(requestParameters: GetConnectionTemplatesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ConnectionTemplateDTO>>> {
        if (requestParameters.systemId === null || requestParameters.systemId === undefined) {
            throw new runtime.RequiredError('systemId','Required parameter requestParameters.systemId was null or undefined when calling getConnectionTemplates.');
        }

        if (requestParameters.xXORGID === null || requestParameters.xXORGID === undefined) {
            throw new runtime.RequiredError('xXORGID','Required parameter requestParameters.xXORGID was null or undefined when calling getConnectionTemplates.');
        }

        const queryParameters: any = {};

        if (requestParameters.systemId !== undefined) {
            queryParameters['systemId'] = requestParameters.systemId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xXORGID !== undefined && requestParameters.xXORGID !== null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters.xXORGID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/connectionTemplates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConnectionTemplateDTOFromJSON));
    }

    /**
     */
    async getConnectionTemplates(requestParameters: GetConnectionTemplatesRequest, initOverrides?: RequestInit): Promise<Array<ConnectionTemplateDTO>> {
        const response = await this.getConnectionTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
