/* tslint:disable */
/* eslint-disable */
/**
 * api-connections
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Unknown version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PostCallbackRequest {
    xXORGID: string;
}

/**
 * 
 */
export class MagentoCallbackControllerApi extends runtime.BaseAPI {

    /**
     */
    async postCallbackRaw(requestParameters: PostCallbackRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.xXORGID === null || requestParameters.xXORGID === undefined) {
            throw new runtime.RequiredError('xXORGID','Required parameter requestParameters.xXORGID was null or undefined when calling postCallback.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xXORGID !== undefined && requestParameters.xXORGID !== null) {
            headerParameters['XX-ORG-ID'] = String(requestParameters.xXORGID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("auth0_bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/callback/magento`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postCallback(requestParameters: PostCallbackRequest, initOverrides?: RequestInit): Promise<void> {
        await this.postCallbackRaw(requestParameters, initOverrides);
    }

}
